'use strict';
// Additive browser evidence: all runtime files, images, CSS, clocks and motion
// remain untouched. Natural screenshots are never relabelled as new runs.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const q=require('../matchup-breakdown/qa.cjs');
const controls=require('./controls-audit.cjs');
const ROOT=q.ROOT,HOME='.page[data-page="home"]',SPORTS=['nfl','nba','nrl','ufc'];
const args=process.argv.slice(2),arg=(k,d)=>args.includes(k)?args[args.indexOf(k)+1]:d;
const engine=arg('--engine','chromium'),base=arg('--base','http://127.0.0.1:8876/project-dollers/');
const out=path.resolve(arg('--output','qa/home-gem/final-'+engine));
assert.ok(['chromium','webkit'].includes(engine));assert.ok(!fs.existsSync(out),'New immutable evidence directory required');fs.mkdirSync(out,{recursive:true});
const sha=q.SHA,runtime=q.runtimeManifest(),canonical=sha(Buffer.from(JSON.stringify(Object.fromEntries(Object.keys(runtime).sort().map(k=>[k,runtime[k]]))))),selfHash=sha(fs.readFileSync(__filename));
assert.equal(canonical,arg('--runtime-sha',canonical),'Explicit accepted frozen runtime');
const originalTests=q.tests(),controlsHash=sha(fs.readFileSync(path.join(__dirname,'controls-audit.cjs')));
const report={status:'running',engine,base,startedAt:new Date().toISOString(),runtimeManifest:runtime,runtimeManifestSha256:canonical,helperSha256:selfHash,
 approvedSource:'Latest four-sport sapphire / blue-red / emerald / ruby Home render attached in chat, 9 October 2026. Original attachment binary is unavailable to this runner.',
 originalTestFiles:originalTests,controlsHelperSha256:controlsHash,interactionSourceContracts:controls.auditActualInteractions(),
 qualification:{actualBrowser:true,deviceScaleFactor:2,naturalMotion:true,animationClockSubstitution:false,DOMOrCSSSubstitution:false,responseSubstitution:false,physicalIPhone:false,strictTLS:base.startsWith('https:'),nativeOSReducedMotionPreference:true,hiddenTabVisibility:false},results:[],originals:[]};
let browser;const save=()=>fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2)+'\n');save();
async function active(page,id='home'){await page.waitForFunction(v=>document.querySelector('.page.active')?.dataset.page===v,id);assert.equal(await page.locator('.page:visible').count(),1);}
async function ready(page){await page.waitForFunction(()=>document.documentElement.dataset.dataReady==='true'&&window.PD_DATA?.roster?.length>0);await page.evaluate(async()=>document.fonts.ready);}
async function naturalMotion(page){
 const sample=()=>page.locator(HOME).evaluate(home=>({state:home.dataset.homeMotionState,reason:home.dataset.homeMotionReason,
  counts:{circuits:home.querySelectorAll('.home-gem-selector-circuit').length,paths:home.querySelectorAll('.home-gem-selector-circuit path').length,glints:home.querySelectorAll('.home-gem-glint').length},
  paths:[...home.querySelectorAll('.home-gem-selector-circuit path')].map(e=>{const s=getComputedStyle(e);return{owner:e.closest('[data-home-select]').dataset.homeSelect,part:e.getAttribute('class'),dash:s.strokeDashoffset,d:e.getAttribute('d'),play:s.animationPlayState,animation:s.animationName,pathLength:e.getAttribute('pathLength'),pointer:s.pointerEvents};}),
  glints:[...home.querySelectorAll('.home-gem-glint')].map(e=>{const s=getComputedStyle(e);return{part:e.className,opacity:s.opacity,transform:s.transform,duration:s.animationDuration,delay:s.animationDelay,play:s.animationPlayState,animation:s.animationName};}),
  ring:[...home.querySelectorAll('.aperture-neon-runner,.aperture-metal-runner')].map(e=>{const s=getComputedStyle(e);return{part:e.getAttribute('class'),dash:s.strokeDashoffset,play:s.animationPlayState,animation:s.animationName};}),
  animations:home.getAnimations({subtree:true}).filter(a=>a.effect?.getComputedTiming().iterations===Infinity).map(a=>({name:a.animationName,target:a.effect?.target?.getAttribute?.('class'),currentTime:a.currentTime,playState:a.playState}))}));
 const first=await sample();assert.equal(first.state,'running');assert.deepEqual(first.counts,{circuits:4,paths:12,glints:12});assert.ok(first.ring.length>=2,'Metal track has native travelling lights');
 for(const p of first.paths){assert.equal(p.play,'running');assert.equal(p.pathLength,'1000');assert.match(p.d,/96.*84/,'Actual rectangle track includes complete sides and corners');assert.equal(p.pointer,'none','Travelling paint cannot intercept buttons');}
 const samples=[first];for(let n=0;n<3;n++){await page.waitForTimeout(470);samples.push(await sample());}
 for(let n=0;n<12;n++)assert.ok(samples.some(s=>s.paths[n].dash!==first.paths[n].dash),'Every sport circuit path advances naturally '+first.paths[n].owner+'/'+first.paths[n].part);
 for(let n=0;n<first.ring.length;n++)assert.ok(samples.some(s=>s.ring[n].dash!==first.ring[n].dash),'Metal ring path advances naturally');
 const durations=first.glints.map(g=>parseFloat(g.duration));assert.ok(durations.every(n=>n>=5.8&&n<=14));assert.ok(new Set(first.glints.map(g=>g.delay)).size>=6,'Glints have independent naturally authored phases');
 await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>document.querySelector('.page.active')?.dataset.homeMotionState==='reduced');
 const reducedFirst=await sample();await page.waitForTimeout(350);const reducedSecond=await sample();
 assert.ok(reducedSecond.animations.every(a=>a.playState!=='running'),'Reduced preference stops every infinite native Home clock');
 assert.ok(reducedSecond.paths.every(p=>p.animation==='none'));assert.ok(reducedSecond.glints.every(p=>p.animation==='none'));assert.ok(reducedSecond.ring.every(p=>p.animation==='none'));
 assert.deepEqual(reducedFirst.paths.map(p=>p.dash),reducedSecond.paths.map(p=>p.dash));
 await page.emulateMedia({reducedMotion:'no-preference'});await page.waitForFunction(()=>document.querySelector('.page.active')?.dataset.homeMotionState==='running');const resumed=await sample();assert.deepEqual(resumed.counts,first.counts,'Preference changes cannot duplicate motion decorations');
 return{status:'passed',samples,reducedFirst,reducedSecond,resumed,qualification:'Read-only computed values and actual animation objects sampled during natural elapsed time. Reduced motion uses a native browser media preference; no clock seeking, synthetic lifecycle event, CSS or DOM modifications.'};
}
async function geometry(page){return page.locator(HOME).evaluate(home=>{const box=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom};};const rect=s=>{const e=home.querySelector(s);return e?box(e):null;};const scroll=home.querySelector('.page-scroll');const images=[...home.querySelectorAll('img')].filter(i=>i.checkVisibility()).map(i=>{const b=box(i),s=getComputedStyle(i),scale=(s.objectFit==='cover'?Math.max:Math.min)(b.width/i.naturalWidth,b.height/i.naturalHeight);return{src:new URL(i.currentSrc||i.src).pathname,natural:[i.naturalWidth,i.naturalHeight],rendered:[b.width,b.height],objectFit:s.objectFit,density:1/scale};});const controls=[...home.querySelectorAll('[data-home-select],[data-home-entry],.bottom-nav button')].map(e=>{const b=box(e),hit=document.elementFromPoint(b.x+b.width/2,b.y+b.height/2);return{label:e.innerText,kind:e.hasAttribute('data-home-select')?'selector':e.hasAttribute('data-home-entry')?'entry':'nav',sport:e.dataset.homeSelect,disabled:e.disabled,selected:e.getAttribute('aria-pressed'),hitTarget:hit===e||e.contains(hit),...b};});return{sport:home.dataset.homeSport,motion:home.dataset.homeMotionState,viewport:{width:innerWidth,height:innerHeight},documentWidth:document.documentElement.scrollWidth,scrollWidth:scroll.scrollWidth,scrollClientWidth:scroll.clientWidth,scrollHeight:scroll.scrollHeight,scrollClientHeight:scroll.clientHeight,brand:rect('.brand'),gate:rect('.aperture-gate'),venue:rect('.aperture-venue'),entry:rect('[data-home-entry]'),dock:rect('.home-sport-dock'),nav:rect('.bottom-nav'),images,controls,animations:home.getAnimations({subtree:true}).map(a=>({name:a.animationName,target:a.effect?.target?.className,playState:a.playState,currentTime:a.currentTime}))};});}
async function run(viewport){const r={viewport,status:'running',errors:{javascript:[],console:[],http:[],failed:[],external:[]},actions:[],captures:[]};report.results.push(r);save();const context=await browser.newContext({viewport,deviceScaleFactor:2,isMobile:viewport.width<700,hasTouch:viewport.width<700,timezoneId:'Australia/Sydney'});const page=await context.newPage();page.setDefaultTimeout(20000);const origin=new URL(base).origin;page.on('pageerror',e=>r.errors.javascript.push(e.message));page.on('console',e=>{if(e.type()==='error')r.errors.console.push(e.text());});page.on('response',e=>{if(e.status()>=400)r.errors.http.push({url:e.url(),status:e.status()});});page.on('requestfailed',e=>r.errors.failed.push({url:e.url(),error:e.failure()?.errorText}));page.on('request',e=>{if(new URL(e.url()).origin!==origin)r.errors.external.push(e.url());});
 try{const response=await page.goto(base+'#home',{waitUntil:'networkidle'});assert.equal(response.status(),200);assert.equal(sha(await response.body()),runtime['index.html']);await ready(page);await active(page);
  for(const sport of SPORTS){const button=page.locator(HOME+' [data-home-select="'+sport+'"]');if(viewport.width<700)await button.tap();else await button.click();r.actions.push({kind:viewport.width<700?'tap':'click',selector:'[data-home-select="'+sport+'"]',at:new Date().toISOString()});await page.waitForFunction(s=>document.querySelector('.page.active')?.dataset.homeSport===s,sport);await page.waitForFunction(()=>[...document.querySelectorAll('.page.active img')].filter(i=>i.checkVisibility()).every(i=>i.complete&&i.naturalWidth>0));await page.waitForFunction(()=>document.querySelector('.page.active')?.dataset.homeMotionState==='running');await page.waitForTimeout(320);const layout=await geometry(page);assert.ok(layout.documentWidth<=viewport.width+1);assert.ok(layout.scrollWidth<=layout.scrollClientWidth+1);for(const image of layout.images){assert.ok(image.src.endsWith('.svg')||image.density>=1.95,'Vector or true Retina image '+image.src);assert.ok(['contain','cover','scale-down','none'].includes(image.objectFit),'Proportional image fit '+image.src);}assert.equal(layout.controls.filter(c=>c.kind==='selector'&&c.selected==='true').length,1);for(const c of layout.controls){assert.ok(c.width>=44&&c.height>=44,'44px native target '+c.label);assert.ok(c.x>=-1&&c.right<=viewport.width+1);assert.ok(c.disabled||c.hitTarget,'Control actually receives native input '+c.label);if(viewport.width<700)assert.ok(c.y>=-1&&c.bottom<=viewport.height+1,'Primary controls fit mobile viewport '+c.label);}const file=engine+'-'+viewport.width+'-'+sport+'.png',bytes=await page.screenshot({path:path.join(out,file)});const capture={file,sha256:sha(bytes),bytes:bytes.length,capturedAt:new Date().toISOString(),sport,viewport,layout};r.captures.push(capture);report.originals.push({file,sha256:capture.sha256,bytes:bytes.length,sport,viewport});save();}
  if(viewport.width<700){await page.locator(HOME+' [data-home-select="nfl"]').tap();r.motion=await naturalMotion(page);r.nativeControls=await controls.controlsAudit(page,{base,viewport,recordAction:action=>r.actions.push(action)});}
  else {r.nativeControls=await controls.auditHomeNative(page,{touch:false,reload:true});}
  if(base.startsWith('https:')&&viewport.width===430){report.servedRuntime=await page.evaluate(async files=>{const rows=[];for(let i=0;i<files.length;i+=6)rows.push(...await Promise.all(files.slice(i,i+6).map(async file=>{const response=await fetch(file,{cache:'no-store'}),bytes=await response.arrayBuffer();return{file,status:response.status,bytes:bytes.byteLength,contentEncoding:response.headers.get('content-encoding'),contentLength:response.headers.get('content-length'),sha256:[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(v=>v.toString(16).padStart(2,'0')).join('')};})));return rows;},Object.keys(runtime));for(const row of report.servedRuntime){assert.equal(row.status,200,row.file);assert.equal(row.sha256,runtime[row.file],row.file);}assert.equal(report.servedRuntime.length,Object.keys(runtime).length);save();}
  r.errors.cancelledNavigation=r.errors.failed.filter(e=>['net::ERR_ABORTED','Load request cancelled'].includes(e.error));r.errors.failed=r.errors.failed.filter(e=>!r.errors.cancelledNavigation.includes(e));
  for(const key of ['javascript','console','http','failed','external'])assert.deepEqual(r.errors[key],[]);r.status='passed';
 }catch(e){r.status='failed';r.failure={message:e.message,stack:e.stack};try{const file=engine+'-'+viewport.width+'-failure.png',bytes=await page.screenshot({path:path.join(out,file)});r.failureOriginal={file,sha256:sha(bytes)};}catch{}throw e;}finally{r.completedAt=new Date().toISOString();save();await context.close();}}
(async()=>{try{browser=await q.launch(engine,base.startsWith('https:'));report.browserVersion=browser.version();const viewports=[{width:393,height:852},{width:430,height:896}];if(args.includes('--responsive'))viewports.push({width:768,height:1024},{width:1440,height:1000});for(const viewport of viewports)await run(viewport);assert.deepEqual(q.runtimeManifest(),runtime);assert.deepEqual(q.tests(),originalTests);assert.equal(sha(fs.readFileSync(path.join(__dirname,'controls-audit.cjs'))),controlsHash);assert.equal(sha(fs.readFileSync(__filename)),selfHash);report.status='passed';report.runtimeUnchanged=true;report.helperUnchanged=true;report.originalTestsUnchanged=true;}catch(e){report.status='failed';report.failure={message:e.message,stack:e.stack};process.exitCode=1;}finally{if(browser)await browser.close();report.browserClosed=true;report.completedAt=new Date().toISOString();save();fs.writeFileSync(path.join(out,'originals.json'),JSON.stringify({status:report.status,runtimeManifestSha256:canonical,originals:report.originals},null,2)+'\n');console.log(JSON.stringify({status:report.status,engine,report:path.relative(ROOT,path.join(out,'results.json')),sha256:sha(fs.readFileSync(path.join(out,'results.json'))),failure:report.failure}));}})();
