'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const {ROOT,launch,runtimeManifest,freePort,WAIT,ready,active,images,SHA}=require('/workspace/project-dollers/qa/team-details/qa.cjs');
const out=path.join(ROOT,'qa/team-details/reviews/integration/home-webkit-paint-probe');
assert.equal(fs.existsSync(out),false,'Keep prior diagnostic output immutable');
fs.mkdirSync(out,{recursive:true});
const expected=JSON.parse(fs.readFileSync(path.join(ROOT,'qa/team-details/published-runtime-manifest.json')));
const report={status:'running',scope:'Untampered native WPE Team-to-Home transition paint diagnostic',engine:'webkit',startedAt:new Date().toISOString(),runtimeManifestSha256:SHA(fs.readFileSync(path.join(ROOT,'qa/team-details/published-runtime-manifest.json'))),testSha256:SHA(fs.readFileSync(__filename)),qualification:'Genuine unpaused screenshots and computed native times; no animation seeking, animation pause/resume, response mocking, source styles, media or runtime changes.',cases:[]};
function save(){fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));}
async function snapshot(page){return page.evaluate(()=>{const root=document.querySelector('.page.active'),describe=e=>{if(!e)return null;const s=getComputedStyle(e),b=e.getBoundingClientRect();return{tag:e.tagName,id:e.id,class:e.className,hidden:e.hidden,opacity:s.opacity,visibility:s.visibility,display:s.display,transform:s.transform,animationName:s.animationName,animationDuration:s.animationDuration,animationPlayState:s.animationPlayState,zIndex:s.zIndex,filter:s.filter,maskImage:s.maskImage,position:s.position,rect:{x:b.x,y:b.y,width:b.width,height:b.height},text:(e.innerText||'').trim().slice(0,140)};};return{performanceTime:performance.now(),date:new Date().toISOString(),hash:location.hash,visibility:document.visibilityState,active:root?.dataset.page,homeMotion:root?.dataset.homeMotionState,ancestors:[root,root?.parentElement,document.body,document.documentElement].map(describe),content:[root?.querySelector('.page-scroll'),root?.querySelector('.brand'),root?.querySelector('.aperture-gate'),root?.querySelector('.home-entry'),root?.querySelector('.bottom-nav')].map(describe),animations:root?.getAnimations({subtree:true}).map(a=>({name:a.animationName,id:a.id,target:a.effect?.target?.className,pseudo:a.effect?.pseudoElement||null,time:a.currentTime,state:a.playState,pending:a.pending,timing:a.effect?.getComputedTiming()})),images:[...root.querySelectorAll('img')].map(i=>({src:i.currentSrc,complete:i.complete,naturalWidth:i.naturalWidth,naturalHeight:i.naturalHeight})),inlineStyles:[root,root?.parentElement,document.body,document.documentElement].map(e=>e?.getAttribute('style'))};});}
async function shot(page,c,label){await page.bringToFront();const bytes=await page.screenshot({path:path.join(out,label+'.png'),animations:'allow'});const record={label,file:label+'.png',sha256:SHA(bytes),bytes:bytes.length,snapshot:await snapshot(page)};c.shots.push(record);save();process.stdout.write(label+' captured\n');return record;}
(async()=>{let server,browser;try{assert.deepEqual(runtimeManifest(),expected);const port=await freePort(),base=`http://127.0.0.1:${port}/project-dollers/`;server=spawn('python3',['-u','-m','http.server',String(port),'--bind','127.0.0.1','--directory',path.dirname(ROOT)],{stdio:'ignore'});for(let n=0;n<40;n++){try{if((await fetch(base)).status===200)break;}catch{}await WAIT(100);}browser=await launch('webkit');report.browserVersion=browser.version();
for(const viewport of[{width:393,height:852},{width:430,height:896}]){const context=await browser.newContext({viewport,deviceScaleFactor:2,isMobile:true,hasTouch:true,timezoneId:'Australia/Sydney'}),page=await context.newPage(),c={viewport,status:'running',shots:[],errors:[]};report.cases.push(c);page.on('pageerror',e=>c.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')c.errors.push(m.text());});
await page.goto(base+'#team/DAL',{waitUntil:'networkidle'});await ready(page);await active(page);await images(page);await page.reload({waitUntil:'networkidle'});await ready(page);await active(page);await images(page);
await page.locator('.page[data-page="team-details"] .bottom-nav [data-open="home"]').scrollIntoViewIfNeeded();await page.locator('.page[data-page="team-details"] .bottom-nav [data-open="home"]').tap();await active(page,'home');await images(page);
await shot(page,c,`home-${viewport.width}-immediate`);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await shot(page,c,`home-${viewport.width}-two-natural-frames`);await page.waitForTimeout(500);await shot(page,c,`home-${viewport.width}-later-500ms`);await page.waitForTimeout(1500);await shot(page,c,`home-${viewport.width}-later-2000ms`);
c.finalSnapshot=await snapshot(page);assert.equal(c.finalSnapshot.active,'home');assert.equal(c.finalSnapshot.ancestors[0].opacity,'1');assert.deepEqual(c.errors,[]);c.status='completed-diagnostic';await context.close();save();}
assert.deepEqual(runtimeManifest(),expected);report.runtimeUnchanged=true;report.status='completed-diagnostic';
}catch(error){report.status='failed-diagnostic';report.failure={message:error.message,stack:error.stack};process.exitCode=1;}finally{if(browser)await browser.close();if(server)server.kill('SIGTERM');report.completedAt=new Date().toISOString();save();process.stdout.write(path.join(out,'results.json')+'\n');}})();
