'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const ROOT='/workspace/project-dollers',q=require(ROOT+'/qa/matchup-breakdown/qa.cjs'),OUT=ROOT+'/qa/home-reference-correction/hosted-data-follow-up',BASE='https://dinkyjunior.github.io/project-dollers/',HOME='[data-page="home"]',SHA=b=>crypto.createHash('sha256').update(b).digest('hex');
assert.ok(!fs.existsSync(OUT),'Fresh immutable output required');fs.mkdirSync(OUT,{recursive:true});fs.copyFileSync(__filename,OUT+'/executed-helper.cjs');
const previous=JSON.parse(fs.readFileSync(ROOT+'/qa/home-reference-correction/hosted-webkit/results.json')),source=Object.fromEntries(Object.keys(previous.source).map(p=>[p,SHA(fs.readFileSync(ROOT+'/'+p))]));assert.deepEqual(source,previous.source,'Every final Home input remains exactly unchanged');
const bookPaths=['current.json','matchup-breakdown.json','player-history.json','provenance.json','roster-source.json','snapshot.js','team-details.json'].map(p=>'assets/data/'+p),dataBodies=Object.fromEntries(bookPaths.map(p=>[p,SHA(fs.readFileSync(ROOT+'/'+p))])),currentValue=JSON.parse(fs.readFileSync(ROOT+'/assets/data/current.json'));
const r={status:'running',startedAt:new Date().toISOString(),productionCommit:'f61ba289a49425a5e9dbe4bf3f94948a60140f0d',pagesRun:38013206902,base:BASE,engine:'webkit',strictTLS:true,viewport:{width:393,height:852},deviceScaleFactor:2,source,dataBodies,previousHomeReportSha256:SHA(fs.readFileSync(ROOT+'/qa/home-reference-correction/hosted-webkit/results.json')),helperSha256:SHA(fs.readFileSync(__filename)),nativeInputs:true,DOMStyleClockResponseSubstitution:false,physicalIPhone:false,actions:[],originals:[],errors:[],http:[],failures:[]};
let browser,ctx;const save=()=>fs.writeFileSync(OUT+'/results.json',JSON.stringify(r,null,2)+'\n');save();
async function ready(page,id){await page.waitForFunction(v=>document.querySelector('.page.active')?.dataset.page===v,id);if(id==='nfl')await page.waitForFunction(()=>document.documentElement.dataset.dataReady==='true'&&window.PD_DATA?.roster?.length);await page.evaluate(async()=>document.fonts.ready);await page.waitForFunction(()=>[...document.querySelectorAll('.page.active img')].filter(i=>i.checkVisibility()).every(i=>i.complete&&i.naturalWidth>0));await page.bringToFront();}
async function capture(page,file){await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const bytes=await page.screenshot({path:OUT+'/'+file,animations:'allow'});r.originals.push({file,sha256:SHA(bytes),bytes:bytes.length,naturalAnimationPhase:true});}
async function clocks(page){return page.locator(HOME).evaluate(h=>{const els=[...h.querySelectorAll('*')];return{at:performance.now(),state:h.dataset.homeMotionState,reason:h.dataset.homeMotionReason,opacity:getComputedStyle(h).opacity,transform:getComputedStyle(h).transform,clocks:h.getAnimations({subtree:true}).filter(a=>a.effect?.getComputedTiming().iterations===Infinity).map(a=>({name:a.animationName,index:els.indexOf(a.effect.target),pseudo:a.effect.pseudoElement||null,time:a.currentTime,state:a.playState}))};});}
(async()=>{try{browser=await q.launch('webkit',true);r.browser=browser.version();ctx=await browser.newContext({viewport:r.viewport,deviceScaleFactor:2,isMobile:true,hasTouch:true});const page=await ctx.newPage();page.on('pageerror',e=>r.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')r.errors.push(m.text());});page.on('response',v=>{if(v.status()>=400)r.http.push({url:v.url(),status:v.status()});});page.on('requestfailed',v=>r.failures.push({url:v.url(),error:v.failure()?.errorText}));const response=await page.goto(BASE+'#home',{waitUntil:'networkidle'});assert.equal(response.status(),200);r.rootBody={status:response.status(),sha256:SHA(await response.body())};assert.equal(r.rootBody.sha256,source['index.html']);await ready(page,'home');await capture(page,'home-393x852.png');
r.servedDataBodies=await page.evaluate(async entries=>{const rows=[];for(const [relative,expectedSha256] of entries){const response=await fetch(relative,{cache:'no-store'}),body=await response.arrayBuffer();rows.push({url:response.url,path:relative,status:response.status,bytes:body.byteLength,sha256:[...new Uint8Array(await crypto.subtle.digest('SHA-256',body))].map(v=>v.toString(16).padStart(2,'0')).join(''),expectedSha256});}return rows;},Object.entries(dataBodies));for(const body of r.servedDataBodies){assert.equal(body.status,200);assert.equal(body.sha256,body.expectedSha256);assert.ok(body.bytes>0);}
await page.locator(HOME+' [data-home-entry]').tap();r.actions.push('native Home Enter NFL');await ready(page,'nfl');assert.equal(new URL(page.url()).hash,'#nfl');r.loadedCurrent=await page.evaluate(async()=>{const v=window.PD_DATA,bytes=new TextEncoder().encode(JSON.stringify(v));return{season:v.season,retrievedAt:v.retrievedAt,throughWeek:v.throughWeek,serializedSha256:[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(v=>v.toString(16).padStart(2,'0')).join('')};});assert.equal(r.loadedCurrent.serializedSha256,SHA(Buffer.from(JSON.stringify(currentValue))));await capture(page,'nfl-393x852.png');
await page.locator('[data-page="nfl"] [data-open="home"]').first().tap();r.actions.push('native NFL return Home');await ready(page,'home');assert.equal(new URL(page.url()).hash,'#home');r.returnImmediate=await clocks(page);await page.waitForFunction(()=>{const h=document.querySelector('[data-page="home"]'),a=h.getAnimations({subtree:true}).filter(a=>a.effect?.getComputedTiming().iterations===Infinity);return h.dataset.homeMotionState==='running'&&getComputedStyle(h).opacity==='1'&&a.length===161&&a.every(v=>v.playState==='running');},null,{timeout:10000});r.returnSettled=await clocks(page);await capture(page,'home-returned-393x852-a.png');await page.waitForTimeout(420);await capture(page,'home-returned-393x852-b.png');r.returnLater=await clocks(page);const key=c=>c.name+':'+c.index+':'+c.pseudo,old=new Map(r.returnSettled.clocks.map(c=>[key(c),c]));assert.equal(r.returnLater.clocks.length,old.size);for(const c of r.returnLater.clocks){assert.equal(c.state,'running');assert.ok(old.has(key(c))&&c.time>old.get(key(c)).time+1);}assert.notEqual(r.originals[2].sha256,r.originals[3].sha256);r.qualifications=['Data-only follow-up; previous full two-engine Home suite remains bound to the same exact15 inputs.','Actual new seven dataset bodies and loaded current dataset verified; this does not independently audit every historical fact.','Native settled returning clocks and changed original paints are verified, not immediate delivery, hidden-route retained phase or physical device performance.'];assert.deepEqual(r.errors,[]);assert.deepEqual(r.http,[]);assert.deepEqual(r.failures,[]);r.finalSource=Object.fromEntries(Object.keys(source).map(p=>[p,SHA(fs.readFileSync(ROOT+'/'+p))]));r.finalDataBodies=Object.fromEntries(bookPaths.map(p=>[p,SHA(fs.readFileSync(ROOT+'/'+p))]));assert.deepEqual(r.finalSource,source);assert.deepEqual(r.finalDataBodies,dataBodies);r.sourceStable=true;r.status='passed';}catch(e){r.status='failed';r.failure={message:e.message,stack:e.stack};process.exitCode=1;}finally{if(ctx)await ctx.close();if(browser)await browser.close();r.browserClosed=true;r.completedAt=new Date().toISOString();assert.equal(SHA(fs.readFileSync(__filename)),r.helperSha256);save();console.log(JSON.stringify({status:r.status,report:OUT+'/results.json',sha256:SHA(fs.readFileSync(OUT+'/results.json')),failure:r.failure}));}})();
