'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const ROOT='/workspace/project-dollers',q=require(ROOT+'/qa/matchup-breakdown/qa.cjs'),OUT=ROOT+'/qa/home-reference-correction/hosted-gallery',BASE='https://dinkyjunior.github.io/project-dollers/qa/home-reference-correction/';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
assert.ok(!fs.existsSync(OUT));fs.mkdirSync(OUT,{recursive:true});fs.copyFileSync(__filename,OUT+'/executed-helper.cjs');
const r={status:'running',startedAt:new Date().toISOString(),base:BASE,strictTLS:true,nativeControls:true,DOMStyleClockResponseSubstitution:false,helperSha256:sha(fs.readFileSync(__filename)),expectedHtmlSha256:sha(fs.readFileSync(ROOT+'/qa/home-reference-correction/index.html')),errors:[],http:[],failures:[],states:[],originals:[]};
const save=()=>fs.writeFileSync(OUT+'/results.json',JSON.stringify(r,null,2)+'\n');
let browser,ctx; save();
async function imagesReady(page){await page.waitForFunction(()=>[...document.querySelectorAll('.comparison img')].length===2&&[...document.querySelectorAll('.comparison img')].every(i=>i.complete&&i.naturalWidth>0));}
async function capture(page,name){const bytes=await page.screenshot({path:OUT+'/'+name,animations:'allow'});r.originals.push({file:name,sha256:sha(bytes),bytes:bytes.length});}
(async()=>{try{browser=await q.launch('webkit',true);r.browser=browser.version();ctx=await browser.newContext({viewport:{width:1100,height:900},deviceScaleFactor:2});const page=await ctx.newPage();page.on('pageerror',e=>r.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')r.errors.push(m.text());});page.on('response',res=>{if(res.status()>=400)r.http.push({url:res.url(),status:res.status()});});page.on('requestfailed',req=>r.failures.push({url:req.url(),error:req.failure()?.errorText}));
const res=await page.goto(BASE,{waitUntil:'networkidle'});assert.equal(res.status(),200);r.servedHtmlSha256=sha(await res.body());assert.equal(r.servedHtmlSha256,r.expectedHtmlSha256);await imagesReady(page);await capture(page,'gallery-desktop.png');
for(const sport of['nfl','nba','nrl','ufc'])for(const size of['393x852','430x896']){await page.locator('#sport').selectOption(sport);await page.locator('#size').selectOption(size);await imagesReady(page);const s=await page.evaluate(()=>({sport:document.querySelector('#sport').value,size:document.querySelector('#size').value,viewport:innerWidth,width:document.documentElement.scrollWidth,images:[...document.querySelectorAll('.comparison img')].map(i=>({id:i.id,src:i.currentSrc,width:i.naturalWidth,height:i.naturalHeight,href:i.closest('a').href}))}));assert.equal(s.sport,sport);assert.equal(s.size,size);assert.ok(s.width<=s.viewport);for(const i of s.images){assert.ok(i.width>0&&i.height>0);assert.equal(i.src,i.href);assert.ok(i.src.endsWith('home-'+sport+'-'+size+'.png'));}r.states.push(s);save();}
const afterResponse=page.waitForResponse(res=>res.url().endsWith('/final-webkit/home-ufc-430x896.png')&&res.request().isNavigationRequest());await page.locator('#after-link').click();const afterNavigation=await afterResponse;await page.waitForURL('**/final-webkit/home-ufc-430x896.png');r.afterLink={url:page.url(),status:afterNavigation.status()};assert.equal(r.afterLink.status,200);await page.goBack({waitUntil:'networkidle'});await imagesReady(page);await page.locator('#sport').selectOption('nfl');await page.locator('#size').selectOption('393x852');await imagesReady(page);const beforeResponse=page.waitForResponse(res=>res.url().endsWith('/home-continuous/hosted-webkit/home-nfl-393x852.png')&&res.request().isNavigationRequest());await page.locator('#before-link').click();const beforeNavigation=await beforeResponse;await page.waitForURL('**/home-continuous/hosted-webkit/home-nfl-393x852.png');r.beforeLink={url:page.url(),status:beforeNavigation.status()};assert.equal(r.beforeLink.status,200);await page.goBack({waitUntil:'networkidle'});await imagesReady(page);
await page.setViewportSize({width:393,height:852});await imagesReady(page);r.mobile=await page.evaluate(()=>({viewport:innerWidth,width:document.documentElement.scrollWidth,comparisonDisplay:getComputedStyle(document.querySelector('.comparison')).display,columns:getComputedStyle(document.querySelector('.comparison')).gridTemplateColumns}));assert.ok(r.mobile.width<=r.mobile.viewport);await capture(page,'gallery-mobile.png');assert.deepEqual(r.errors,[]);assert.deepEqual(r.http,[]);assert.deepEqual(r.failures,[]);r.status='passed';}catch(e){r.status='failed';r.failure={message:e.message,stack:e.stack};process.exitCode=1;}finally{if(ctx)await ctx.close();if(browser)await browser.close();r.browserClosed=true;r.completedAt=new Date().toISOString();assert.equal(sha(fs.readFileSync(__filename)),r.helperSha256);save();console.log(JSON.stringify({status:r.status,report:OUT+'/results.json',sha256:sha(fs.readFileSync(OUT+'/results.json')),failure:r.failure}));}})();
