'use strict';
const fs=require('node:fs'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const ROOT='/workspace/project-dollers',q=require(ROOT+'/qa/matchup-breakdown/qa.cjs'),OUT=ROOT+'/qa/home-reference-correction/hosted-reduced-motion-repro',BASE='https://dinkyjunior.github.io/project-dollers/',HOME='[data-page="home"]',sha=b=>crypto.createHash('sha256').update(b).digest('hex');
assert.ok(!fs.existsSync(OUT));fs.mkdirSync(OUT,{recursive:true});fs.copyFileSync(__filename,OUT+'/executed-helper.cjs');
const source=JSON.parse(fs.readFileSync(ROOT+'/qa/home-reference-correction/final-webkit/results.json')).source,r={status:'running',startedAt:new Date().toISOString(),base:BASE,strictTLS:true,source,helperSha256:sha(fs.readFileSync(__filename)),nativeMediaEmulation:true,DOMStyleClockResponseSubstitution:false,results:[]};
let browser;const save=()=>fs.writeFileSync(OUT+'/results.json',JSON.stringify(r,null,2)+'\n'); save();
async function sample(page){return page.locator(HOME).evaluate(h=>({at:performance.now(),reduced:matchMedia('(prefers-reduced-motion:reduce)').matches,state:h.dataset.homeMotionState,reason:h.dataset.homeMotionReason,active:h.classList.contains('active'),visibility:document.visibilityState,clocks:h.getAnimations({subtree:true}).filter(a=>a.effect?.getComputedTiming().iterations===Infinity).map(a=>({name:a.animationName,time:a.currentTime,state:a.playState,pending:a.pending,targetClass:a.effect.target.getAttribute('class'),pseudo:a.effect.pseudoElement||null,cssPlay:getComputedStyle(a.effect.target,a.effect.pseudoElement).animationPlayState}))}));}
async function paint(page,file){const bytes=await page.screenshot({path:OUT+'/'+file,animations:'allow'});return{file,sha256:sha(bytes),bytes:bytes.length};}
(async()=>{try{browser=await q.launch('webkit',true);r.browser=browser.version();for(const viewport of[{width:393,height:852},{width:430,height:896}]){const ctx=await browser.newContext({viewport,deviceScaleFactor:2,isMobile:true,hasTouch:true}),page=await ctx.newPage(),row={viewport,errors:[],http:[],failures:[],samples:[]};r.results.push(row);page.on('pageerror',e=>row.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')row.errors.push(m.text());});page.on('response',v=>{if(v.status()>=400)row.http.push({url:v.url(),status:v.status()});});page.on('requestfailed',v=>row.failures.push({url:v.url(),error:v.failure()?.errorText}));try{const res=await page.goto(BASE+'#home',{waitUntil:'networkidle'});assert.equal(res.status(),200);assert.equal(sha(await res.body()),source['index.html']);await page.evaluate(async()=>document.fonts.ready);await page.waitForFunction(()=>[...document.querySelectorAll('.page.active img')].filter(i=>i.checkVisibility()).every(i=>i.complete&&i.naturalWidth>0));await page.bringToFront();row.initialPaint=await paint(page,`home-${viewport.width}-initial.png`);row.initial=await sample(page);await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(300);row.reducedPaint=await paint(page,`home-${viewport.width}-reduced.png`);row.reduced=await sample(page);assert.equal(row.reduced.reduced,true);assert.equal(row.reduced.clocks.filter(x=>x.state==='running').length,0);row.restoreRequestedAt=await page.evaluate(()=>performance.now());await page.emulateMedia({reducedMotion:'no-preference'});row.immediate=await sample(page);for(const [label,wait] of[['paint-0',0],['paint-400',400],['paint-1000',600],['paint-2000',1000]]){if(wait)await page.waitForTimeout(wait);const before=await sample(page),p=await paint(page,`home-${viewport.width}-${label}.png`),after=await sample(page);row.samples.push({label,before,paint:p,after});save();console.log(JSON.stringify({viewport:viewport.width,label,actualElapsed:after.at-row.restoreRequestedAt,media:after.reduced,state:after.state,count:after.clocks.length,running:after.clocks.filter(x=>x.state==='running').length}));}row.status='captured';}finally{await ctx.close();save();}}r.sourceStable=Object.entries(source).every(([p,h])=>sha(fs.readFileSync(ROOT+'/'+p))===h);r.status='captured';}catch(e){r.status='failed';r.failure={message:e.message,stack:e.stack};process.exitCode=1;}finally{if(browser)await browser.close();r.browserClosed=true;r.completedAt=new Date().toISOString();assert.equal(sha(fs.readFileSync(__filename)),r.helperSha256);save();console.log(JSON.stringify({status:r.status,report:OUT+'/results.json',sha256:sha(fs.readFileSync(OUT+'/results.json')),failure:r.failure}));}})();
