'use strict';
// Additive contracts for the latest Home request. Native app pixels, controls,
// browser preference and clocks only; historical helpers/tests remain untouched.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const q=require('../matchup-breakdown/qa.cjs');
const args=process.argv.slice(2),arg=(k,d)=>args.includes(k)?args[args.indexOf(k)+1]:d;
const engine=arg('--engine','chromium'),base=arg('--base','http://127.0.0.1:8876/project-dollers/');
const out=path.resolve(arg('--output','qa/home-continuous/local-'+engine));
const hosted=base.startsWith('https:'),HOME='[data-page="home"]',SPORTS=['nfl','nba','nrl','ufc'];
const iteration=args.includes('--iteration');
const VIEWPORTS=[{width:393,height:852},{width:430,height:896},...(engine==='chromium'&&!iteration?[{width:768,height:1024},{width:1440,height:1000}]:[])];
const MAIN='M657.5 50 A539 478 0 1 1 657.5 1006 A539 478 0 1 1 657.5 50Z';
assert.ok(['chromium','webkit'].includes(engine));assert.equal(new URL(base).pathname,'/project-dollers/');
assert.ok(!fs.existsSync(out),'Fresh immutable output required');
const runtime=q.runtimeManifest(),canonical=q.SHA(Buffer.from(JSON.stringify(Object.fromEntries(Object.keys(runtime).sort().map(k=>[k,runtime[k]])))));
assert.equal(canonical,arg('--runtime-sha'),'Explicit frozen runtime required');
const tests=q.tests(),self=q.SHA(fs.readFileSync(__filename));
const sources=Object.fromEntries(['current','team-details','matchup-breakdown'].map(k=>[k,JSON.parse(fs.readFileSync(path.join(q.ROOT,'assets/data/'+k+'.json')))]));
fs.mkdirSync(out,{recursive:true});
const report={status:'running',phase:iteration?'functional-iteration-not-frozen-acceptance':'frozen-runtime-native-validation',engine,base,strictTLS:hosted,startedAt:new Date().toISOString(),runtimeManifest:runtime,runtimeManifestSha256:canonical,originalTestFiles:tests,helperSha256:self,qualification:{actualBrowser:true,naturalMotion:true,deviceScaleFactor:2,DOMOrCSSSubstitution:false,responseSubstitution:false,animationClockSubstitution:false,physicalIPhone:false,approvedChatBinaryAvailable:false,registeredReferencePixelComparison:false,historicalHomeNavAndTitleTestsSuperseded:true},results:[],originals:[]};
let browser;const save=()=>fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2)+'\n');save();
async function ready(page,id){
 await page.waitForFunction(v=>document.querySelector('.page.active')?.dataset.page===v&&document.documentElement.dataset.dataReady==='true'&&window.PD_DATA?.roster?.length,id);
 if(id==='team-details')await page.waitForFunction(()=>document.documentElement.dataset.teamDataReady==='true'&&window.PDTeamDetails?.getDataset());
 if(id==='matchup-breakdown')await page.waitForFunction(()=>document.documentElement.dataset.matchupDataReady==='true'&&window.MatchupBreakdown?.getDataset());
 await page.evaluate(async()=>document.fonts.ready);assert.equal(await page.locator('.page:visible').count(),1);
}
async function identity(page,kind){
 const row=await page.evaluate(async k=>{const value=k==='current'?window.PD_DATA:k==='team-details'?window.PDTeamDetails.getDataset():window.MatchupBreakdown.getDataset();const bytes=new TextEncoder().encode(JSON.stringify(value));return{season:value.season,throughWeek:value.throughWeek,retrievedAt:value.retrievedAt,serializedSha256:[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(v=>v.toString(16).padStart(2,'0')).join('')};},kind);
 assert.equal(row.serializedSha256,q.SHA(Buffer.from(JSON.stringify(sources[kind]))),'Loaded exact real '+kind+' dataset');return{kind,...row};
}
async function homeState(page){return page.locator(HOME).evaluate(h=>{
 const box=e=>{const b=e.getBoundingClientRect();return{x:b.x,y:b.y,width:b.width,height:b.height,right:b.right,bottom:b.bottom};};
 const s=h.querySelector('.page-scroll'),entry=h.querySelector('[data-home-entry]'),label=entry.querySelector('[data-home-entry-label]'),brand=h.querySelector('.brand'),mark=h.querySelector('.home-brand-mark'),lighting=h.querySelector('.home-brand-lighting');
 const controls=[...h.querySelectorAll('[data-home-select],[data-home-entry]')].map(e=>{const b=box(e),hit=document.elementFromPoint(b.x+b.width/2,b.y+b.height/2),style=getComputedStyle(e);return{sport:e.dataset.homeSelect,text:e.innerText,label:e.getAttribute('aria-label'),pressed:e.getAttribute('aria-pressed'),disabled:e.disabled,hit:hit===e||e.contains(hit),background:style.backgroundImage,...b};});
 return{page:h.dataset.page,active:h.classList.contains('active'),sport:h.dataset.homeSport,state:h.dataset.homeMotionState,reason:h.dataset.homeMotionReason,viewport:{width:innerWidth,height:innerHeight},pageRect:box(h),documentWidth:document.documentElement.scrollWidth,scroll:{width:s.scrollWidth,clientWidth:s.clientWidth,height:s.scrollHeight,clientHeight:s.clientHeight,top:s.scrollTop},navCount:h.querySelectorAll('.bottom-nav,nav').length,brand:{rect:box(brand),mark:box(mark),lighting:lighting?box(lighting):null,crystalLetters:[...h.querySelectorAll('.home-brand-crystal-letter')].map(g=>({letter:g.dataset.brandLetter,clip:g.getAttribute('clip-path'),points:g.querySelectorAll('.home-brand-point').length})),goldLetters:[...h.querySelectorAll('.home-brand-gold-letter')].map(g=>({letter:g.dataset.brandLetter,clip:g.getAttribute('clip-path'),points:g.querySelectorAll('.home-brand-point').length})),pointTransforms:[...h.querySelectorAll('.home-brand-point')].map(p=>p.getAttribute('transform')),goldReflectionOpacity:[...h.querySelectorAll('.home-brand-gold-reflection')].map(p=>Number(getComputedStyle(p).opacity))},gate:{rect:box(h.querySelector('.aperture-gate')),venue:box(h.querySelector('.aperture-venue')),clip:getComputedStyle(h.querySelector('.aperture-venue')).clipPath,mainPaths:[...h.querySelectorAll('.aperture-neon-bloom,.aperture-neon-track,.aperture-neon-core,.aperture-neon-runner')].map(p=>p.getAttribute('d')),housing:[...h.querySelectorAll('.aperture-metal-housing,.home-metal-reflection-image')].map(i=>({src:i.currentSrc,visible:i.checkVisibility(),fit:getComputedStyle(i).objectFit}))},entry:{...box(entry),text:label.innerText,disabled:entry.disabled,open:entry.getAttribute('data-open'),label:entry.getAttribute('aria-label'),font:getComputedStyle(label).font,color:getComputedStyle(label).color,fill:getComputedStyle(label).webkitTextFillColor,textRect:box(label),face:getComputedStyle(entry,'::before').backgroundImage,gradient:getComputedStyle(label).backgroundImage},dock:box(h.querySelector('.home-sport-dock')),controls,images:[...h.querySelectorAll('img')].filter(i=>i.checkVisibility()).map(i=>({src:i.currentSrc,naturalWidth:i.naturalWidth,naturalHeight:i.naturalHeight,fit:getComputedStyle(i).objectFit,...box(i)}))};
 });}
async function homeContract(page,sport){
 await ready(page,'home');await page.waitForFunction(()=>[...document.querySelectorAll('.page.active img')].filter(i=>i.checkVisibility()).every(i=>i.complete&&i.naturalWidth>0));
 const h=await homeState(page);assert.equal(h.active,true);assert.equal(h.sport,sport);assert.equal(h.navCount,0,'Home bottom navigation is removed from real DOM');
 assert.ok(h.documentWidth<=h.viewport.width+1&&h.scroll.width<=h.scroll.clientWidth+1,'No horizontal overflow');
 assert.equal(h.controls.length,5,'Four selectors and one entry control');
 assert.equal(h.controls.filter(c=>c.sport&&c.pressed==='true').length,1);
 for(const c of h.controls){assert.ok(c.width>=44&&c.height>=44,'44px native target '+c.label);assert.ok(c.x>=h.pageRect.x-1&&c.right<=h.pageRect.right+1&&c.y>=h.pageRect.y-1&&c.bottom<=h.pageRect.bottom+1,'Native control fits framed viewport '+c.label);if(!c.disabled)assert.equal(c.hit,true,'Unobscured native target '+c.label);if(c.sport){assert.equal(c.text.trim(),'','Selectors have no visible names');assert.match(c.label,new RegExp('Select '+c.sport,'i'));}}
 assert.deepEqual(h.gate.mainPaths,[MAIN,MAIN,MAIN,MAIN],'Continuous expanded elliptical main channel');
 assert.equal(h.gate.housing.length,4);for(const i of h.gate.housing)assert.ok(i.src.endsWith('/assets/home/continuous-gate.svg'),'Native continuous vector casting');
 assert.match(h.gate.clip,/ellipse\(/,'Expanded elliptical field opening');
 assert.ok(h.gate.rect.width/h.gate.rect.height>1.08&&h.gate.rect.width/h.gate.rect.height<1.12,'1315x1197 gate ratio');
 assert.equal(h.entry.disabled,sport!=='nfl');assert.equal(h.entry.open,sport==='nfl'?'nfl':null);
 assert.equal(h.entry.text,sport==='nfl'?'Enter':sport.toUpperCase()+' · Coming soon');
 assert.match(h.entry.face,new RegExp('entry-crystal-'+sport+'\\.svg'),'Native vector crystal CTA per sport');
 assert.ok(h.entry.textRect.width>30&&h.entry.textRect.height>10&&h.entry.textRect.x>=h.entry.x&&h.entry.textRect.right<=h.entry.right,'Actual CTA text has readable native glyph geometry');
 assert.equal(h.brand.crystalLetters.length,7);assert.equal(h.brand.goldLetters.length,6);
 assert.deepEqual(h.brand.crystalLetters.map(v=>v.letter),['P','R','O','J','E','C','T']);
 for(const g of h.brand.crystalLetters)assert.ok(g.points>=10&&g.clip,'Every PROJECT letter has clipped facet scintillation');
 for(const g of h.brand.goldLetters)assert.ok(g.points>=3&&g.clip,'Every gold letter has clipped warm reflections');
 for(const key of ['x','y','width','height'])assert.ok(Math.abs(h.brand.mark[key]-h.brand.lighting[key])<.6,'Native lighting shares original brand coordinate bounds '+key);
 for(const opacity of h.brand.goldReflectionOpacity)assert.ok(opacity<=.2,'Gold reflections retain underlying letter surfaces');
 for(const i of h.images){assert.ok(i.naturalWidth>0&&i.naturalHeight>0,'Native image decoded '+i.src);assert.ok(['cover','contain','none','scale-down'].includes(i.fit),'Native proportional image fit '+i.src);}
 return h;
}
async function snapshot(page,r,label,sport){
 assert.equal(await page.locator('.page.active').getAttribute('data-page'),sport?'home':await page.locator('.page.active').getAttribute('data-page'));
 const proof=await q.capture(page,out,label);report.originals.push({...proof,sport,viewport:r.viewport});save();return proof;
}
async function motionSample(page){return page.locator(HOME).evaluate(h=>{const elements=[...h.querySelectorAll('*')];return{state:h.dataset.homeMotionState,reason:h.dataset.homeMotionReason,active:h.classList.contains('active'),clocks:h.getAnimations({subtree:true}).filter(a=>a.effect?.getComputedTiming().iterations===Infinity).map(a=>({name:a.animationName,index:elements.indexOf(a.effect.target),class:a.effect.target?.getAttribute('class'),pseudo:a.effect.pseudoElement||null,state:a.playState,time:a.currentTime})),paths:[...h.querySelectorAll('.home-gem-selector-circuit path,.aperture-neon-runner,.aperture-metal-runner')].map(e=>({class:e.getAttribute('class'),dash:getComputedStyle(e).strokeDashoffset,play:getComputedStyle(e).animationPlayState})),brandPoints:[...h.querySelectorAll('.home-brand-point')].map(e=>({class:e.getAttribute('class'),opacity:getComputedStyle(e).opacity,play:getComputedStyle(e).animationPlayState}))};});}
async function naturalMotion(page,r){
 const m={status:'running',frames:[],samples:[]};r.motion=m;save();await page.waitForFunction(()=>document.querySelector('[data-page="home"]').dataset.homeMotionState==='running');
 for(let i=0;i<4;i++){if(i)await page.waitForTimeout(470);m.frames.push(await snapshot(page,r,'home-nfl-'+r.viewport.width+'x'+r.viewport.height+'-natural-'+i,'nfl'));m.samples.push(await motionSample(page));save();}
 assert.equal(new Set(m.frames.map(v=>v.sha256)).size,m.frames.length,'Natural native frames differ');
 const first=m.samples[0];assert.ok(first.clocks.some(c=>c.name.includes('brand-crystal')&&c.state==='running'),'Native PROJECT clocks run');
 for(let i=0;i<first.paths.length;i++)assert.ok(m.samples.some(s=>s.paths[i].dash!==first.paths[i].dash),'Every selector/ring circuit naturally advances '+first.paths[i].class);
 assert.ok(m.samples.some(s=>s.brandPoints.some((p,i)=>p.opacity!==first.brandPoints[i].opacity)),'Facet-mounted PROJECT/gold points naturally scintillate');
 await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(180);m.reduced=await motionSample(page);assert.equal(m.reduced.state,'reduced');assert.equal(m.reduced.clocks.filter(c=>c.state==='running').length,0,'Reduced motion disables Home infinite lighting');m.reducedCapture=await snapshot(page,r,'home-nfl-'+r.viewport.width+'x'+r.viewport.height+'-reduced','nfl');
 await page.emulateMedia({reducedMotion:'no-preference'});await page.waitForFunction(()=>document.querySelector('[data-page="home"]').dataset.homeMotionState==='running');m.resumed=await motionSample(page);m.status='passed';save();
}
async function served(page){const rows=await page.evaluate(async files=>{const rows=[];for(let i=0;i<files.length;i+=6)rows.push(...await Promise.all(files.slice(i,i+6).map(async file=>{const r=await fetch(file,{cache:'no-store'}),bytes=await r.arrayBuffer();return{file,status:r.status,bytes:bytes.byteLength,sha256:[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(v=>v.toString(16).padStart(2,'0')).join('')};})));return rows;},Object.keys(runtime));
 assert.equal(rows.length,Object.keys(runtime).length);for(const row of rows){assert.equal(row.status,200,'Actual runtime HTTP200 '+row.file);assert.equal(row.sha256,runtime[row.file],'Actual runtime body identity '+row.file);}return rows;}
async function run(viewport,last){
 const mobile=viewport.width<700,r={viewport,status:'running',actions:[],captures:[],identities:[],routes:[],errors:{javascript:[],console:[],http:[],failed:[],external:[]}};report.results.push(r);save();
 const context=await browser.newContext({viewport,deviceScaleFactor:2,isMobile:mobile,hasTouch:mobile,timezoneId:'Australia/Sydney'}),page=await context.newPage();page.setDefaultTimeout(20000);const origin=new URL(base).origin;
 page.on('pageerror',e=>r.errors.javascript.push(e.message));page.on('console',e=>{if(e.type()==='error')r.errors.console.push(e.text());});page.on('response',e=>{if(e.status()>=400)r.errors.http.push({url:e.url(),status:e.status()});});page.on('requestfailed',e=>r.errors.failed.push({url:e.url(),error:e.failure()?.errorText}));page.on('request',e=>{if(new URL(e.url()).origin!==origin)r.errors.external.push(e.url());});
 const action=async selector=>{if(mobile)await page.locator(selector).tap();else await page.locator(selector).click();r.actions.push({kind:mobile?'native-tap':'native-click',selector,at:new Date().toISOString(),url:page.url()});};
 const navigate=async(url,reload=false)=>{if(!reload&&page.url().split('#')[0]===url.split('#')[0])await page.goto('about:blank');const response=reload?await page.reload({waitUntil:'networkidle'}):await page.goto(url,{waitUntil:'networkidle'});assert.ok(response,'Actual document navigation yields an HTTP response');assert.equal(response.status(),200);assert.equal(q.SHA(await response.body()),runtime['index.html']);r.actions.push({kind:reload?'native-reload':'native-direct-url',url:page.url(),status:200,indexSha256:runtime['index.html']});};
 try{
  await navigate(base+'#home');await ready(page,'home');r.identities.push(await identity(page,'current'));
  for(const sport of SPORTS){await action(HOME+' [data-home-select="'+sport+'"]');await page.waitForTimeout(180);const layout=await homeContract(page,sport),proof=await snapshot(page,r,'home-'+sport+'-'+viewport.width+'x'+viewport.height,sport);r.captures.push({...proof,sport,layout});save();console.log(JSON.stringify({captured:path.relative(q.ROOT,path.join(out,proof.file)),sport,viewport}));
   if(sport!=='nfl'){const e=layout.entry;if(mobile)await page.touchscreen.tap(e.x+e.width/2,e.y+e.height/2);else await page.mouse.click(e.x+e.width/2,e.y+e.height/2);r.actions.push({kind:'native-unavailable-entry-pointer',sport});await ready(page,'home');assert.equal(await page.locator(HOME).getAttribute('data-home-sport'),sport);assert.match(await page.locator(HOME+' .home-availability').textContent(),/coming soon/i);}
  }
  await navigate(page.url(),true);await ready(page,'home');assert.equal(await page.locator(HOME).getAttribute('data-home-sport'),'ufc','Real session storage persists selected sport on refresh');r.persistence='passed';
  await page.locator(HOME+' [data-home-select="ufc"]').focus();await page.keyboard.press('Home');r.actions.push({kind:'native-keyboard',key:'Home'});await homeContract(page,'nfl');await page.keyboard.press('ArrowRight');r.actions.push({kind:'native-keyboard',key:'ArrowRight'});await homeContract(page,'nba');await page.keyboard.press('End');r.actions.push({kind:'native-keyboard',key:'End'});await homeContract(page,'ufc');await action(HOME+' [data-home-select="nfl"]');
  if(mobile)await naturalMotion(page,r);
  await action(HOME+' [data-home-entry]');await ready(page,'nfl');assert.equal(new URL(page.url()).hash,'#nfl');r.identities.push(await identity(page,'current'));
  await page.waitForFunction(()=>document.querySelector('[data-page="home"]').dataset.homeMotionReason==='inactive');r.inactiveHome=await motionSample(page);assert.equal(r.inactiveHome.clocks.filter(c=>c.state==='running').length,0,'Inactive Home animation clocks pause');
  r.routes.push({page:'nfl',geometry:await require('../nfl-dashboard/qa.cjs').geometry(page),capture:await snapshot(page,r,'nfl-'+viewport.width+'x'+viewport.height)});
  for(const tab of ['players','recap','ladder']){await action('[data-page="nfl"] [data-nfl-tab="'+tab+'"]');assert.equal(await page.locator('[data-page="nfl"] [data-nfl-tab="'+tab+'"]').getAttribute('aria-selected'),'true','Protected NFL tab remains functional '+tab);}
  await page.locator('#week-select').focus();await page.keyboard.press('Home');await page.keyboard.press('Tab');r.actions.push({kind:'native-keyboard-week',key:'Home'});assert.ok(await page.locator('#week-select').inputValue());await page.locator('#week-select').focus();await page.keyboard.press('End');await page.keyboard.press('Tab');r.actions.push({kind:'native-keyboard-week',key:'End'});
  await action('[data-page="nfl"] [data-conference="NFC"]');const toggle='[data-page="nfl"] [data-standings-toggle]';if(await page.locator(toggle).getAttribute('aria-expanded')!=='true')await action(toggle);
  const team='[data-page="nfl"] [data-nfl-action="team"][data-team="DAL"]';if(await page.locator(team).getAttribute('aria-expanded')!=='true')await action(team);await action('[data-page="nfl"] [data-nfl-action="team-details"][data-team="DAL"]');await ready(page,'team-details');assert.equal(await page.evaluate(()=>window.PDTeamDetails.getState().team),'DAL');r.identities.push(await identity(page,'team-details'));
  r.routes.push({page:'team-details',geometry:await require('../team-details/qa.cjs').geometry(page),capture:await snapshot(page,r,'team-dal-'+viewport.width+'x'+viewport.height)});
  const upcoming='[data-page="team-details"] .td-upcoming [data-td-action="matchup"]',game=await page.locator(upcoming).getAttribute('data-game');assert.ok(game);await action(upcoming);await ready(page,'matchup-breakdown');assert.equal(await page.evaluate(()=>window.MatchupBreakdown.getState().game),game);r.identities.push(await identity(page,'matchup-breakdown'));
  r.routes.push({page:'matchup-breakdown',fixture:game,geometry:await q.geometry(page),capture:await snapshot(page,r,'matchup-dal-'+viewport.width+'x'+viewport.height)});
  await navigate(page.url(),true);await ready(page,'matchup-breakdown');assert.equal(await page.evaluate(()=>window.MatchupBreakdown.getState().game),game);r.identities.push(await identity(page,'matchup-breakdown'));
  await action('[data-page="matchup-breakdown"] .mb-back[data-mb-action="back"]');await ready(page,'team-details');assert.equal(await page.evaluate(()=>window.PDTeamDetails.getState().team),'DAL');await action('[data-page="team-details"] .td-back[data-td-action="ladder"]');await ready(page,'nfl');await action('[data-page="nfl"] [data-open="home"]');await ready(page,'home');await page.waitForFunction(()=>document.querySelector('[data-page="home"]').dataset.homeMotionState==='running');r.returnHome=await homeContract(page,'nfl');
  for(const [route,id] of [['#nfl','nfl'],['#team/PIT','team-details'],['#matchup/DAL','matchup-breakdown'],['#home','home']]){await navigate(base+route);await ready(page,id);if(id==='team-details')assert.equal(await page.evaluate(()=>window.PDTeamDetails.getState().team),'PIT');await navigate(page.url(),true);await ready(page,id);r.routes.push({kind:'direct-url-and-refresh',route,page:id});}
  if(last&&!iteration)r.servedRuntime=await served(page);r.identities.push(await identity(page,'current'));
  r.errors.cancelledNavigation=r.errors.failed.filter(e=>['net::ERR_ABORTED','Load request cancelled'].includes(e.error));r.errors.failed=r.errors.failed.filter(e=>!r.errors.cancelledNavigation.includes(e));for(const key of ['javascript','console','http','failed','external'])assert.deepEqual(r.errors[key],[],'Actual browser '+key+' empty');r.status='passed';
 }catch(e){r.status='failed';r.failure={message:e.message,stack:e.stack};throw e;}finally{await context.close();r.contextClosed=true;r.completedAt=new Date().toISOString();save();}
}
async function compactViewports(){
 const rows=[];for(const viewport of [{width:320,height:700},{width:852,height:393}]){const context=await browser.newContext({viewport,deviceScaleFactor:2,hasTouch:viewport.width<700,isMobile:viewport.width<700}),page=await context.newPage();try{await page.goto(base+'#home',{waitUntil:'networkidle'});await ready(page,'home');const top=await homeState(page);assert.ok(top.documentWidth<=viewport.width+1&&top.scroll.width<=top.scroll.clientWidth+1);const before=await q.capture(page,out,'compact-home-'+viewport.width+'x'+viewport.height+'-top');await page.mouse.move(top.pageRect.x+top.pageRect.width/2,Math.min(viewport.height-10,top.pageRect.bottom-10));await page.mouse.wheel(0,2000);await page.waitForTimeout(180);const bottom=await homeState(page);assert.ok(bottom.documentWidth<=viewport.width+1&&bottom.scroll.width<=bottom.scroll.clientWidth+1);for(const c of bottom.controls){assert.ok(c.width>=44&&c.height>=44);assert.ok(c.x>=bottom.pageRect.x-1&&c.right<=bottom.pageRect.right+1);assert.ok(c.y>=bottom.pageRect.y-1&&c.bottom<=bottom.pageRect.bottom+1,'Compact native scroll exposes controls '+c.label);if(!c.disabled)assert.equal(c.hit,true);}rows.push({viewport,top,bottom,before,after:await q.capture(page,out,'compact-home-'+viewport.width+'x'+viewport.height+'-bottom'),nativeWheelScroll:true});}finally{await context.close();}}return rows;
}
(async()=>{try{browser=await q.launch(engine,hosted);report.browserVersion=browser.version();for(let i=0;i<VIEWPORTS.length;i++)await run(VIEWPORTS[i],i===VIEWPORTS.length-1);if(engine==='chromium'&&!iteration)report.compactViewports=await compactViewports();if(!iteration){assert.deepEqual(q.runtimeManifest(),runtime,'Frozen runtime unchanged throughout native checks');report.runtimeUnchanged=true;}else report.finalRuntimeManifest=q.runtimeManifest();assert.deepEqual(q.tests(),tests,'Historical tests/helpers untouched');assert.equal(q.SHA(fs.readFileSync(__filename)),self);report.originalTestsUnchanged=true;report.helperUnchanged=true;report.status='passed';}catch(e){report.status='failed';report.failure={message:e.message,stack:e.stack};process.exitCode=1;}finally{if(browser)await browser.close();report.browserClosed=true;report.completedAt=new Date().toISOString();save();console.log(JSON.stringify({status:report.status,engine,report:path.relative(q.ROOT,path.join(out,'results.json')),runtimeManifestSha256:canonical,sha256:q.SHA(fs.readFileSync(path.join(out,'results.json'))),failure:report.failure}));}})();
