"""Present untouched actual hosted PNGs, preserving their natural capture pixels."""
from pathlib import Path
import hashlib,html,json
root=Path(__file__).resolve().parent;out=root/'live-captures';out.mkdir(exist_ok=True)
images=[];sections=[]
for directory,viewport in [('hosted-webkit-mobile','393x852'),('hosted-webkit-mobile','430x896'),('hosted-webkit-desktop','1440x1000')]:
 report=root/directory/'results.json'; data=json.loads(report.read_bytes());assert data['status']=='passed' and data['hosted'] and data['unchangedDuringQA']; assert all(r['status']=='passed' for r in data['results']);figures=[]
 for suffix,label in [('top','Native top'),('scroll-2','Native lower scroll'),('full-content','Entire content — qualified capture-only exposure')]:
  p=root/directory/f'nfl-{viewport}-{suffix}.png';assert p.exists(),p;src='../'+str(p.relative_to(root));images.append({'path':str(p.relative_to(root)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size}); width=400 if viewport.startswith('1440') else int(viewport.split('x')[0]);figures.append(f'<figure><figcaption>{html.escape(label)}</figcaption><a href="{src}"><img src="{src}" width="{width}" loading="lazy" alt="Actual hosted NFL {viewport} {html.escape(label)}"></a></figure>')
 sections.append(f'<section><h2>WebKit · {viewport.replace("x"," × ")}</h2><div class="views">'+''.join(figures)+'</div></section>')
content='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="../../../assets/favicon.svg"><title>Project Dollar — actual hosted NFL</title><style>body{margin:0;background:#040a10;color:#eef8ff;font:16px/1.5 system-ui,sans-serif}main{max-width:1400px;margin:auto;padding:24px}h1{font-size:25px}a{color:#62dcff}p{color:#adc6d7}section{margin:24px 0;border-top:1px solid #176088}.views{display:flex;gap:20px;align-items:flex-start;overflow-x:auto;padding-bottom:16px}figure{margin:0;flex:0 0 auto}figcaption{font-weight:700;margin:10px 0;max-width:390px}img{display:block;max-width:none;height:auto;border:1px solid #1b566b}</style><main><h1>Actual hosted NFL — original browser screenshots</h1><p>Untouched PNGs captured directly from https://dinkyjunior.github.io/project-dollers/ in genuine WebKit, with certificate verification enabled and no substituted responses. Click an image for its original resolution.</p><p>Native top and lower-scroll views show the actual compact enclosure. Full-content screenshots temporarily expose internal scrolling in a separate app page for capture; they do not represent a taller physical phone. Desktop PNGs are displayed at 400 pixels here for comparison; the original image retains the entire desktop viewport.</p><p>The current verified source context and retrieval timestamp are preserved. Its statistics differ from the approved concept's sample values. The approved visual reference was the chat attachment; no registered pixel identity, hardware frame-rate or Safari-control coverage is claimed.</p><p><a href="../index.html">Before/after comparisons</a> · <a href="../RELEASE.md">Release evidence</a> · <a href="../../../#nfl">Open NFL</a></p>'''+''.join(sections)+'</main></html>'
(out/'index.html').write_text(content);(out/'image-hashes.json').write_text(json.dumps(images,indent=2)+'\n');print('Hosted gallery built from',len(images),'unaltered PNGs')
