'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {spawn,execFileSync}=require('node:child_process'),{once}=require('node:events');
const {ROOT,NFL,launch,runtimeManifest,SHA,WAIT,ready,active,geometry,images,capture,freePort}=require(path.resolve(__dirname,'../..')+'/qa/nfl-dashboard/qa.cjs');
const {paintRail}=require('./paint-rail.cjs');
const args=process.argv.slice(2),arg=k=>{const i=args.indexOf(k);return i<0?null:args[i+1];};
const engine=arg('--engine'),out=arg('--output'),manifestPath=arg('--manifest'),freeze=arg('--freeze'),hosted=arg('--base');
assert.ok(['chromium','webkit'].includes(engine));assert.ok(out&&manifestPath&&/^[a-f0-9]{64}$/.test(freeze||''));assert.ok(!fs.existsSync(out),'Do not overwrite prior QA');fs.mkdirSync(out,{recursive:true});
const frozen=fs.readFileSync(manifestPath),manifest=runtimeManifest();assert.equal(SHA(frozen),freeze);assert.deepEqual(manifest,JSON.parse(frozen));
const data=JSON.parse(fs.readFileSync(ROOT+'/assets/data/current.json'));
const report={status:'running',engine,hosted:!!hosted,startedAt:new Date().toISOString(),source:{gitHead:execFileSync('git',['rev-parse','HEAD'],{cwd:ROOT,encoding:'utf8'}).trim(),runtimeFiles:manifest,frozenManifestSha256:freeze},qualification:{genuineNativeBrowser:true,physicalIPhone:false,deviceScaleFactor:2,noResponseOrAppDataSubstitution:true,strictTLS:!!hosted,naturalAnimationPhase:true,scope:'Actual same-origin manual refresh at both phone sizes, exact response body and source time, focus, geometry, direct reload and console/network checks. Complete controls/motion/regression suites are separate.'},results:[]};let server,browser,base=hosted;
(async()=>{try{if(!base){const port=await freePort();base=`http://127.0.0.1:${port}/${encodeURIComponent(path.basename(ROOT))}/`;server=spawn('python3',['-u','-m','http.server',String(port),'--bind','127.0.0.1','--directory',path.dirname(ROOT)],{stdio:'ignore'});for(let i=0;i<30;i++){try{if((await fetch(base)).status===200)break;}catch{}await WAIT(100);}}if(!base.endsWith('/'))base+='/';report.base=base;browser=await launch(engine,!!hosted);report.browserVersion=browser.version();
for(const viewport of[{width:393,height:852},{width:430,height:896}]){const context=await browser.newContext({viewport,deviceScaleFactor:2,isMobile:true,hasTouch:true,timezoneId:'Australia/Sydney'}),page=await context.newPage(),result={viewport,status:'running'},errors=[],http=[],failed=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',r=>{if(r.status()>=400)http.push({url:r.url(),status:r.status()});});page.on('requestfailed',r=>failed.push({url:r.url(),message:r.failure()?.errorText}));page.on('request',r=>{const u=new URL(r.url());if(!['data:','blob:','about:'].includes(u.protocol)&&u.origin!==new URL(base).origin)external.push(u.href);});
try{assert.equal((await page.goto(base+'#nfl',{waitUntil:'networkidle'})).status(),200);await ready(page);await active(page,'nfl');await images(page);assert.deepEqual(await page.evaluate(()=>window.PD_DATA),data);result.initialGeometry=await geometry(page);assert.deepEqual(result.initialGeometry.clipped,[]);await page.waitForFunction(()=>window.PD_UPDATE_STATUS&&window.PD_UPDATE_STATUS.state!=='checking');const old=await page.evaluate(()=>window.PD_UPDATE_STATUS),responsePromise=page.waitForResponse(r=>new URL(r.url()).pathname.endsWith('/assets/data/current.json')&&r.request().method()==='GET').then(response=>({response}),error=>({error}));const refresh=page.locator(NFL+' [data-refresh]');await refresh.focus();await refresh.click();const pending=await responsePromise;if(pending.error)throw pending.error;const response=pending.response;assert.equal(response.status(),200);await response.finished();const bytes=await response.body();assert.equal(SHA(bytes),manifest['assets/data/current.json'],'Actual HTTP body matches frozen data');await page.waitForFunction(last=>window.PD_UPDATE_STATUS?.reason==='manual'&&window.PD_UPDATE_STATUS.state==='unchanged'&&window.PD_UPDATE_STATUS.lastCheckedAt!==last,old.lastCheckedAt);assert.deepEqual(await page.evaluate(()=>window.PD_DATA),data);assert.equal(await page.evaluate(()=>document.activeElement?.matches('[data-refresh]')),true,'Focused refresh control retained');const status=await page.evaluate(()=>window.PD_UPDATE_STATUS);assert.equal(status.sourceRetrievedAt,data.retrievedAt);result.manualRefresh={url:response.url(),httpStatus:response.status(),responseBytes:bytes.length,sha256:SHA(bytes),status,focusPreserved:true};
await page.locator(NFL+' #data-status [data-sources]').click();await page.locator('#sources-dialog').waitFor({state:'visible'});const time=await page.evaluate(t=>new Date(t).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'}),data.retrievedAt);result.sourceDialog=await page.locator('#sources-content').innerText();assert.ok(result.sourceDialog.includes('Retrieved '+time),'Exact retrieval timestamp in Sources');await page.keyboard.press('Escape');await page.locator('#sources-dialog').waitFor({state:'hidden'});await page.reload({waitUntil:'networkidle'});await ready(page);await active(page,'nfl');await images(page);assert.deepEqual(await page.evaluate(()=>window.PD_DATA),data);result.directReload=true;result.finalGeometry=await geometry(page);assert.deepEqual(result.finalGeometry.clipped,[]);await page.evaluate(async()=>{await Promise.all([...document.querySelectorAll('.page.active img')].filter(i=>i.checkVisibility()).map(i=>i.decode?.().catch(()=>{})));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});result.finalCapture=await capture(page,out,`nfl-${viewport.width}x${viewport.height}-refreshed-final`);if(args.includes('--rail-glyph'))result.newFrameGlyphPaint=await paintRail(page,out,`nfl-${viewport.width}x${viewport.height}`);result.errors={javascriptAndConsole:errors,http,external,transport:failed.filter(f=>!['net::ERR_ABORTED','Load request cancelled'].includes(f.message)),cancelled:failed.filter(f=>['net::ERR_ABORTED','Load request cancelled'].includes(f.message))};for(const k of['javascriptAndConsole','http','external','transport'])assert.deepEqual(result.errors[k],[]);result.status='passed';}catch(e){result.status='failed';result.failure={message:e.message,stack:e.stack,errors,http,failed,external};try{await page.screenshot({path:path.join(out,`failure-${viewport.width}.png`)});}catch{}}finally{await context.close();}report.results.push(result);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));console.log(`${engine} ${viewport.width} ${result.status}`);}
report.unchangedDuringQA=JSON.stringify(runtimeManifest())===JSON.stringify(manifest);assert.ok(report.unchangedDuringQA);report.status=report.results.every(r=>r.status==='passed')?'passed':'failed';}catch(e){report.status='failed';report.failure={message:e.message,stack:e.stack};}finally{if(browser)await browser.close();if(server){server.kill('SIGTERM');if(server.exitCode===null)await once(server,'exit');}report.completedAt=new Date().toISOString();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));console.log(path.join(out,'results.json'));process.exitCode=report.status==='passed'?0:1;}})();
