'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),q=require('../matchup-breakdown/qa.cjs');
const expected='50be3e13e78530564490d55436d2edead921b258499ce6fb6a8f8ec2fb3d69b1',runtime=q.runtimeManifest(),sha=q.SHA;
assert.equal(sha(Buffer.from(JSON.stringify(Object.fromEntries(Object.keys(runtime).sort().map(k=>[k,runtime[k]]))))),expected);assert.equal(Object.keys(runtime).length,273);
const tests=q.tests(),nativeHash=sha(fs.readFileSync(path.join(__dirname,'native.cjs'))),companionHash=sha(fs.readFileSync(path.join(__dirname,'current-chromium.cjs')));
assert.equal(nativeHash,'127f252aae5332ec26a830f69abeec16acc0b1fa3ee2edb173aeca26234e37a8');assert.equal(companionHash,'3bbbdf7ef4fada832ddd351eb42ee64a1d08dcbcdb593e3f8b74b528fffa49a1');
function read(file,pin){const full=path.join(q.ROOT,file),bytes=fs.readFileSync(full);if(pin)assert.equal(sha(bytes),pin);return{file,sha256:sha(bytes),value:JSON.parse(bytes)};}
const previous=read('qa/home-continuous/local-chromium-final/results.json','675f204e2d80aae97becaaa4c2f58b7bee147d37ce4ffc84c898ae3c94ed36b5');
const webkit=read('qa/home-continuous/local-webkit-current/results.json','e5ff193431a99a826b6ef1c72dc8166d5e9cab9de726ab03e48ddf55edfccd97');
const chrome=read('qa/home-continuous/current-chromium-v2/results.json','3cf70fbb8b50d7847e7f11531221819b696a2aa509b041df7f26f2b9fbb6fa84');
const source=read('qa/home-continuous/reviews/source-delta-94e7.json','59ab2241a2a44298c659b01c2cc8afcbd903c2d91eb1cb623b9ab8a4e9f2249e');
assert.equal(source.value.status,'accepted-current-source-delta-with-evidence-qualifications');assert.equal(source.value.runtimeBinding.runtimeManifestSha256,expected);assert.equal(source.value.runtimeBinding.fileCount,273);for(const b of source.value.actualDataBindings){assert.equal(b.exactIncomingBodyMatch,true);assert.equal(runtime[b.path],b.incomingAndCurrentSha256);}for(const b of source.value.sourceAndTestCodeBindings)assert.equal(sha(fs.readFileSync(path.join(q.ROOT,b.path))),b.sha256);
function validate(r,current,helper){const v=r.value;assert.equal(v.status,'passed');assert.equal(v.browserClosed,true);assert.equal(v.runtimeUnchanged,true);assert.equal(v.helperUnchanged,true);assert.equal(v.originalTestsUnchanged,true);assert.equal(v.helperSha256,helper);assert.deepEqual(v.originalTestFiles,tests);const dir=path.dirname(path.join(q.ROOT,r.file));assert.equal(sha(fs.readFileSync(path.join(dir,'executed-helper.cjs'))),helper);if(current){assert.equal(v.runtimeManifestSha256,expected);assert.deepEqual(v.runtimeManifest,runtime);}for(const row of [...v.results,...(v.coldRoutes||[])]){assert.equal(row.status,'passed');assert.equal(row.contextClosed,true);for(const key of ['javascript','console','http','failed','external'])assert.deepEqual(row.errors[key],[]);}for(const p of v.originals){assert.equal(sha(fs.readFileSync(path.join(dir,p.file))),p.sha256);assert.equal(p.readiness.noStylesClockOrAnimationMutation,true);}return{file:r.file,sha256:r.sha256,engine:v.engine,browserVersion:v.browserVersion,runtimeManifestSha256:v.runtimeManifestSha256,helperSha256:helper,actions:[...v.results,...(v.coldRoutes||[])].reduce((n,r)=>n+r.actions.length,0),untouchedOriginals:v.originals.length,cancelledNavigation:[...v.results,...(v.coldRoutes||[])].flatMap(r=>r.errors.cancelledNavigation||[])};}
const receipts=[validate(previous,false,nativeHash),validate(webkit,true,nativeHash),validate(chrome,true,companionHash)];
for(const r of [webkit.value,chrome.value]){const sets=r.results.filter(v=>v.servedRuntime);assert.equal(sets.length,1);assert.equal(sets[0].servedRuntime.length,273);for(const b of sets[0].servedRuntime){assert.equal(b.status,200);assert.equal(b.sha256,runtime[b.file]);}}
for(const width of [393,430]){const w=webkit.value.results.find(r=>r.viewport.width===width);assert.ok(w);assert.equal(w.captures.length,4);assert.equal(w.motion.status,'passed');assert.equal(w.motion.reduced.reducedPreference,true);assert.equal(w.motion.reduced.state,'reduced');assert.equal(w.motion.reduced.clocks.filter(c=>c.state==='running').length,0);assert.equal(w.inactiveHome.clocks.filter(c=>c.state==='running').length,0);assert.equal(w.returnHome.state,'running');for(const image of w.captures)assert.equal(image.readiness.settled.page,'home');}
assert.equal(chrome.value.coldRoutes.length,8);assert.equal(chrome.value.bridge.unchangedPriorBodies,248);assert.equal(chrome.value.bridge.addedLegacyFallbacks.length,20);assert.equal(chrome.value.previousVisualProof.sha256,previous.sha256);for(const name of ['PIT','NYJ','WAS','LA'])assert.equal(chrome.value.coldRoutes.filter(v=>v.team===name&&v.status==='passed').length,2);
const changed=Object.keys(previous.value.runtimeManifest).filter(k=>previous.value.runtimeManifest[k]!==runtime[k]);assert.deepEqual(changed.sort(),chrome.value.bridge.changedSourceBooks.slice().sort());
const boot=read('qa/home-continuous/local-webkit-current/native-boot-fallback-proof.json');assert.equal(boot.value.browserReportSha256,webkit.sha256);assert.equal(boot.value.bodyHash,runtime['assets/logos/ind.png']);assert.ok(boot.value.observedLines.some(v=>v.text.includes('15:46:04')&&v.text.includes(' 200 ')));
const out=path.join(__dirname,'reviews/native-qa.json');assert.ok(!fs.existsSync(out));
const seal={status:'passed-local-native',completedAt:new Date().toISOString(),runtimeManifestSha256:expected,runtimeFiles:273,nativeHelperSha256:nativeHash,currentCompanionHelperSha256:companionHash,sealHelperSha256:sha(fs.readFileSync(__filename)),reports:receipts,previous253VisualAndMotionBridge:chrome.value.bridge,actualColdPITFallbackProof:{file:boot.file,sha256:boot.sha256,qualification:boot.value.qualification},sourceAudit:{file:source.file,sha256:source.sha256,status:source.value.status,sourceCommit:source.value.sourceCommit,semanticDeltaStatus:source.value.semanticDelta.status,existingChecks:source.value.existingChecks,limits:source.value.limits},originalTestFiles:tests,qualification:{nativePixelsAndControls:true,noCSSDOMSourceResponseOrClockSubstitution:true,earlierChromium253EvidenceNotRelabelled:true,allCurrent273HTTPBodiesVerifiedPerEngine:true,fullMatchupHistoricalSourceSuitePassed:false,physicalIPhoneCertification:false,approvedChatOriginalBinaryAvailable:false,registeredReferencePixelIdentity:false,publicationRuntimeVerified:false}};
fs.writeFileSync(out,JSON.stringify(seal,null,2)+'\n');console.log(JSON.stringify({status:seal.status,file:path.relative(q.ROOT,out),sha256:sha(fs.readFileSync(out)),reports:receipts,sourceAudit:{status:source.value.status,sha256:source.sha256}}));
