'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const Q=require('/workspace/project-dollers/qa/team-details/qa.cjs');
const ROOT=Q.ROOT,OUT='/workspace/recovery-qa/team-assets-motion/legacy-webkit-probe-'+Date.now();
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const manifest=()=>JSON.parse(fs.readFileSync(ROOT+'/qa/team-details/candidate-runtime-manifest.json'));
function readCards(){return [...document.querySelectorAll('.player-card')].filter(c=>c.checkVisibility()).map(card=>{
 const ball=card.querySelector('.orbit-football'),light=card.querySelector('.perimeter-light-core');
 const b=ball.getBoundingClientRect(),r=card.getBoundingClientRect(),s=getComputedStyle(ball),l=getComputedStyle(light);
 const percent=parseFloat(s.offsetDistance),dash=parseFloat(l.strokeDashoffset),phase=((5-dash)%100+100)%100;
 const expected=light.getPointAtLength(light.getTotalLength()*percent/100),p=new DOMPoint(expected.x,expected.y).matrixTransform(light.getScreenCTM());
 const d=Math.abs(percent-phase); const dist={left:Math.abs(b.x+b.width/2-r.left),right:Math.abs(b.x+b.width/2-r.right),top:Math.abs(b.y+b.height/2-r.top),bottom:Math.abs(b.y+b.height/2-r.bottom)};
 const edge=Object.entries(dist).sort((a,b)=>a[1]-b[1])[0];
 return{player:card.getAttribute('aria-label'),percent,dash,phase,phaseDiff:Math.min(d,100-d),trackDistance:Math.hypot(b.x+b.width/2-p.x,b.y+b.height/2-p.y),edge:edge[0],borderDistance:edge[1],timings:[ball,light].map(e=>{const a=e.getAnimations()[0];return{time:a.currentTime,state:a.playState,progress:a.effect.getComputedTiming().progress,timing:a.effect.getTiming()}})};
});}
function summarize(samples){const by={};for(const sample of samples)for(const c of sample){const a=by[c.player]||={samples:0,phaseDiff:0,trackDistance:0,borderDistance:0,edges:[],allRunning:true};a.samples++;a.phaseDiff=Math.max(a.phaseDiff,c.phaseDiff);a.trackDistance=Math.max(a.trackDistance,c.trackDistance);a.borderDistance=Math.max(a.borderDistance,c.borderDistance);if(!a.edges.includes(c.edge))a.edges.push(c.edge);a.allRunning&&=c.timings.every(x=>x.state==='running');}return by;}
(async()=>{fs.mkdirSync(OUT,{recursive:true});const before=manifest(),port=await Q.freePort(),server=spawn('python3',['-m','http.server',String(port),'--bind','127.0.0.1'],{cwd:ROOT,stdio:'ignore'});let browser;const report={status:'running',startedAt:new Date().toISOString(),source:{manifestSha256:sha(fs.readFileSync(ROOT+'/qa/team-details/candidate-runtime-manifest.json')),runtimeFiles:before},qualification:'Targeted genuine native WebKit. Natural samples and PNGs contain no animation/style/source mutation. Separate synthetic-seek diagnostics deliberately pause/seek the test tab; they are not native screenshot evidence.'};try{await Q.WAIT(200);browser=await Q.launch('webkit',false);report.browserVersion=browser.version();const context=await browser.newContext({viewport:{width:393,height:852},deviceScaleFactor:2,isMobile:true,hasTouch:true});const page=await context.newPage();await page.goto('http://127.0.0.1:'+port+'/#steelers',{waitUntil:'networkidle'});await Q.ready(page,false);await Q.active(page,'steelers');await page.waitForFunction(()=>[...document.querySelectorAll('.player-card')].filter(c=>c.checkVisibility()).every(c=>c.classList.contains('motion-track-ready')&&c.querySelector('.perimeter-light-core')));await Q.WAIT(250);
 report.natural=[];for(let i=0;i<21;i++){report.natural.push(await page.evaluate(readCards));if(i===0||i===20){const name='natural-'+i+'.png',bytes=await page.screenshot({path:path.join(OUT,name)});(report.captures||=[]).push({file:name,sha256:sha(bytes)});}if(i<20)await page.waitForTimeout(500);}report.naturalSummary=summarize(report.natural);
 report.syntheticUnpainted=await page.evaluate(()=>[...document.querySelectorAll('.player-card')].filter(c=>c.checkVisibility()).map(card=>{const ball=card.querySelector('.orbit-football'),light=card.querySelector('.perimeter-light-core'),animations=[ball,...card.querySelectorAll('.card-perimeter-light path')].map(e=>e.getAnimations()[0]),timing=animations[0].effect.getTiming();for(const a of animations)a.pause();const samples=[];for(let i=0;i<32;i++){for(const a of animations)a.currentTime=timing.delay+timing.duration+i*timing.duration/32;const b=ball.getBoundingClientRect(),expected=light.getPointAtLength(light.getTotalLength()*i/32),p=new DOMPoint(expected.x,expected.y).matrixTransform(light.getScreenCTM());samples.push({i,trackDistance:Math.hypot(b.x+b.width/2-p.x,b.y+b.height/2-p.y),phaseDiff:Math.abs(parseFloat(getComputedStyle(ball).offsetDistance)-(5-parseFloat(getComputedStyle(light).strokeDashoffset)))});}return{player:card.getAttribute('aria-label'),maxTrackDistance:Math.max(...samples.map(s=>s.trackDistance)),maxPhaseDiff:Math.max(...samples.map(s=>s.phaseDiff)),samples};}));
 report.syntheticPainted=[];for(let i=0;i<32;i++){await page.evaluate(i=>{for(const card of [...document.querySelectorAll('.player-card')].filter(c=>c.checkVisibility())){const ball=card.querySelector('.orbit-football'),animations=[ball,...card.querySelectorAll('.card-perimeter-light path')].map(e=>e.getAnimations()[0]),timing=animations[0].effect.getTiming();for(const a of animations){a.pause();a.currentTime=timing.delay+timing.duration+i*timing.duration/32;}}},i);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));report.syntheticPainted.push(await page.evaluate(readCards));}report.syntheticPaintedSummary=summarize(report.syntheticPainted);report.unchangedDuringRun=JSON.stringify(before)===JSON.stringify(manifest())&&Object.entries(before).every(([f,h])=>sha(fs.readFileSync(ROOT+'/'+f))===h);report.status='diagnosed';report.completedAt=new Date().toISOString();}catch(e){report.status='failed';report.error=e.stack;process.exitCode=1;}finally{if(browser)await browser.close();server.kill();fs.writeFileSync(path.join(OUT,'results.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({out:OUT,status:report.status,natural:report.naturalSummary,unpainted:report.syntheticUnpainted?.map(x=>({player:x.player,maxTrackDistance:x.maxTrackDistance,maxPhaseDiff:x.maxPhaseDiff})),painted:report.syntheticPaintedSummary,unchanged:report.unchangedDuringRun,error:report.error},null,2));}})();
