'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const ROOT='/workspace/project-dollers',q=require(ROOT+'/qa/matchup-breakdown/qa.cjs');
const BASE='http://127.0.0.1:8876/project-dollers/',OUT=ROOT+'/qa/home-synchronized-entrance/local-webkit-resize-settled';
const SHA=b=>crypto.createHash('sha256').update(b).digest('hex'),bound=JSON.parse(fs.readFileSync(ROOT+'/qa/home-synchronized-entrance/local-webkit-corrected/results.json'));
const frozen=()=>Object.fromEntries(Object.keys(bound.source).map(p=>[p,SHA(fs.readFileSync(ROOT+'/'+p))]));
assert.ok(!fs.existsSync(OUT),'Fresh immutable output required');fs.mkdirSync(OUT,{recursive:true});fs.copyFileSync(__filename,OUT+'/executed-helper.cjs');
const report={status:'running',startedAt:new Date().toISOString(),engine:'webkit',base:BASE,source:frozen(),helperSha256:SHA(fs.readFileSync(__filename)),nativeInput:true,DOMStyleClockResponseSubstitution:false,physicalIPhone:false,results:[],qualification:'Targeted native resize-observer settling check, using only actual viewport actions, read-only geometry/clock observations, and untouched natural browser screenshots. No full local suite rerun.'};
assert.deepEqual(report.source,bound.source);const save=()=>fs.writeFileSync(OUT+'/results.json',JSON.stringify(report,null,2)+'\n');save();
let browser;
async function sample(page){return page.locator('[data-page="home"]').evaluate(h=>({observedAt:performance.now(),viewport:{width:innerWidth,height:innerHeight},motionState:h.dataset.homeMotionState,ready:h.dataset.homeLightCircuitReady,geometry:[...h.querySelectorAll('[data-home-select],[data-home-entry]')].map(e=>{const s=getComputedStyle(e),svg=e.querySelector('.home-gem-selector-circuit,.home-gem-entry-circuit'),v=svg.viewBox.baseVal;return{sport:e.dataset.homeSelect||'entry',width:parseFloat(s.width),height:parseFloat(s.height),viewBox:svg.getAttribute('viewBox'),viewBoxWidth:v.width,viewBoxHeight:v.height,matched:Math.abs(v.width-parseFloat(s.width)-4)<.01&&Math.abs(v.height-parseFloat(s.height)-4)<.01,pathD:[...svg.querySelectorAll('path')].map(p=>p.getAttribute('d'))};}),paths:[...h.querySelectorAll('.aperture-neon-runner,.aperture-metal-runner,.home-gem-selector-circuit path,.home-gem-entry-circuit path')].map(p=>({class:p.getAttribute('class'),d:p.getAttribute('d'),pathLength:p.getAttribute('pathLength'),dash:parseFloat(getComputedStyle(p).strokeDashoffset),clocks:p.getAnimations().filter(a=>a.effect?.target===p).map(a=>({name:a.animationName,startTime:a.startTime,time:a.currentTime,state:a.playState,duration:a.effect.getTiming().duration,delay:a.effect.getTiming().delay,infinite:a.effect.getTiming().iterations===Infinity}))}))}));}
async function settled(page){await page.waitForFunction(()=>{const h=document.querySelector('[data-page="home"]'),es=[...h.querySelectorAll('[data-home-select],[data-home-entry]')];return h.dataset.homeLightCircuitReady==='true'&&es.length===5&&es.every(e=>{const s=getComputedStyle(e),v=e.querySelector('.home-gem-selector-circuit,.home-gem-entry-circuit').viewBox.baseVal;return Math.abs(v.width-parseFloat(s.width)-4)<.01&&Math.abs(v.height-parseFloat(s.height)-4)<.01;})&&[...h.querySelectorAll('.aperture-neon-runner,.aperture-metal-runner,.home-gem-selector-circuit path,.home-gem-entry-circuit path')].every(p=>p.getAnimations().some(a=>a.playState==='running'));},null,{timeout:10000});}
function check(s,original){assert.equal(s.geometry.length,5);for(const g of s.geometry)assert.equal(g.matched,true,'Native resize observer matches fractional computed control '+g.sport);assert.equal(s.paths.length,17);const first=s.paths[0].clocks[0];for(let i=0;i<s.paths.length;i++){const p=s.paths[i];assert.equal(p.pathLength,'1000');assert.equal(p.clocks.length,1);const c=p.clocks[0];assert.equal(c.name,'pd-home-aperture-channel');assert.equal(c.duration,8800);assert.equal(c.delay,0);assert.equal(c.state,'running');assert.equal(c.infinite,true);assert.equal(c.startTime,first.startTime);assert.ok(Math.abs(c.time-first.time)<1);if(original){assert.equal(c.startTime,original.paths[i].clocks[0].startTime,'Viewport change preserves each native startTime');assert.ok(c.time>original.paths[i].clocks[0].time,'Native resized clocks advance');}}assert.ok(Math.max(...s.paths.map(p=>p.dash))-Math.min(...s.paths.map(p=>p.dash))<.2);}
async function capture(page,label){await page.bringToFront();await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const file=label+'.png',bytes=await page.screenshot({path:OUT+'/'+file,animations:'allow'});return{file,sha256:SHA(bytes),bytes:bytes.length,at:new Date().toISOString(),naturalAnimationPhase:true};}
(async()=>{try{browser=await q.launch('webkit',false);report.browser=browser.version();for(const [from,to] of [[{width:393,height:852},{width:430,height:896}],[{width:430,height:896},{width:393,height:852}]]){const ctx=await browser.newContext({viewport:from,deviceScaleFactor:2,isMobile:true,hasTouch:true}),page=await ctx.newPage(),r={from,to,errors:[],http:[],failures:[]};report.results.push(r);save();page.on('pageerror',e=>r.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')r.errors.push(m.text());});page.on('response',v=>{if(v.status()>=400)r.http.push({url:v.url(),status:v.status()});});page.on('requestfailed',v=>r.failures.push({url:v.url(),error:v.failure()?.errorText}));try{const res=await page.goto(BASE+'#home',{waitUntil:'networkidle'});assert.equal(res.status(),200);assert.equal(SHA(await res.body()),report.source['index.html']);await page.waitForFunction(()=>document.querySelector('.page.active')?.dataset.page==='home');await page.evaluate(async()=>document.fonts.ready);await page.waitForFunction(()=>[...document.querySelectorAll('.page.active img')].filter(i=>i.checkVisibility()).every(i=>i.complete&&i.naturalWidth>0));if(!report.servedBodies){report.servedBodies=await page.evaluate(async expected=>{const out=[];for(const[file,expectedSha256]of Object.entries(expected)){const response=await fetch(file,{cache:'no-store'}),bytes=await response.arrayBuffer();out.push({file,status:response.status,sha256:[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(v=>v.toString(16).padStart(2,'0')).join(''),expectedSha256});}return out;},report.source);for(const row of report.servedBodies){assert.equal(row.status,200);assert.equal(row.sha256,row.expectedSha256);}}
await settled(page);r.initialOriginal=await capture(page,'home-resize-'+from.width+'-initial');r.initial=await sample(page);check(r.initial);r.resizeRequestedAt=await page.evaluate(()=>performance.now());await page.setViewportSize(to);r.immediate=await sample(page);await settled(page);r.settledOriginal=await capture(page,'home-resize-'+from.width+'-to-'+to.width+'-settled');r.settled=await sample(page);check(r.settled,r.initial);assert.deepEqual(r.settled.viewport,to);r.naturalLaterOriginal=await capture(page,'home-resize-'+from.width+'-to-'+to.width+'-later');r.naturalLater=await sample(page);check(r.naturalLater,r.settled);assert.notEqual(r.settledOriginal.sha256,r.naturalLaterOriginal.sha256,'Untouched resumed resized paint changes naturally');assert.deepEqual(r.errors,[]);assert.deepEqual(r.http,[]);assert.deepEqual(r.failures,[]);r.status='passed';console.log(JSON.stringify({from,to,status:r.status,immediateMatched:r.immediate.geometry.every(g=>g.matched),settledMatched:true}));}finally{await ctx.close();save();}}
report.finalSource=frozen();report.sourceStable=JSON.stringify(report.source)===JSON.stringify(report.finalSource);assert.equal(report.sourceStable,true);report.status='passed';}catch(e){report.status='failed';report.failure={message:e.message,stack:e.stack};process.exitCode=1;}finally{if(browser)await browser.close();report.browserClosed=true;report.completedAt=new Date().toISOString();assert.equal(SHA(fs.readFileSync(__filename)),report.helperSha256);save();console.log(JSON.stringify({status:report.status,browserClosed:true,report:OUT+'/results.json',sha256:SHA(fs.readFileSync(OUT+'/results.json')),failure:report.failure}));}})();
