'use strict';
// Targeted actual-HTTPS verification complements the exhaustive local suites.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const q=require('./qa.cjs'),model=require('./model.cjs');
const args=process.argv.slice(2),arg=n=>args[args.indexOf(n)+1],outArg=args.includes('--output')?arg('--output'):null;
assert.ok(outArg,'Fresh output directory required');
const out=path.resolve(outArg),base=args.includes('--base')?arg('--base'):'https://dinkyjunior.github.io/project-dollers/';
assert.match(base,/^https:\/\//,'Actual verified HTTPS host required');assert.ok(!fs.existsSync(out),'Original hosted evidence is immutable');fs.mkdirSync(out,{recursive:true});
const runtime=q.runtimeManifest(),data=q.sourceData(),expected=q.SHA(Buffer.from(JSON.stringify(data.matchup))),report={status:'running',hosted:true,engine:'webkit',base,startedAt:new Date().toISOString(),source:{runtimeFiles:runtime,testFiles:q.tests(),matchupHash:runtime['assets/data/matchup-breakdown.json']},qualification:{strictTLS:true,sourceSubstitution:false,genuineBrowser:true,deviceScaleFactor:2,physicalIPhone:false,naturalAnimationPhase:true,scope:'Targeted actual hosted release verification; exhaustive control/data/negative-update acceptance belongs to independently bound full local Chromium/WebKit reports.'},results:[]};
const save=()=>fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2)+'\n');save();let browser;
async function scenario(viewport){const mobile=viewport.width<600,context=await browser.newContext({viewport,deviceScaleFactor:2,isMobile:mobile,hasTouch:mobile,timezoneId:'Australia/Sydney'}),page=await context.newPage(),r={viewport,status:'running',nativeInputs:[],startedAt:new Date().toISOString()},errors=[],http=[],failed=[],external=[];report.results.push(r);save();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',s=>{if(s.status()>=400)http.push({url:s.url(),status:s.status()});});page.on('requestfailed',s=>failed.push({url:s.url(),error:s.failure()?.errorText}));await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin===new URL(base).origin||['data:','blob:','about:'].includes(u.protocol))return route.continue();external.push(u.href);return route.abort();});
const click=async(locator,label)=>{assert.equal(await locator.count(),1,label+' unique control');if(mobile)await locator.tap();else await locator.click();r.nativeInputs.push({label,input:mobile?'native-touch':'pointer',hash:new URL(page.url()).hash});};
const exact=async()=>assert.equal((await q.semantic(page)).dataset.sha256,expected,'Actual hosted complete source body equals reviewed snapshot');
const close=async()=>{await click(page.locator('#matchup-breakdown-dialog .dialog-close'),'Close research');await page.locator('#matchup-breakdown-dialog').waitFor({state:'hidden'});};
try{const response=await page.goto(base+'#team/DAL',{waitUntil:'networkidle'});assert.equal(response.status(),200);await q.active(page,'team-details');await page.waitForSelector('[data-upcoming-game]');await click(page.locator('[data-upcoming-game] [data-td-action="matchup"]'),'Dallas → Open Matchup Breakdown');await q.ready(page);await q.active(page);await exact();const upcomingState=await page.evaluate(()=>window.MatchupBreakdown.getState()),expectedUpcoming=data.teamForm.teams.DAL.upcomingGameId,linkedFixture=model.fixture(data.matchup,'DAL',upcomingState),teamFixture=data.teamForm.teams.DAL.games.find(game=>game.id===expectedUpcoming);assert.ok(expectedUpcoming&&teamFixture,'Dallas source has its own upcoming fixture');assert.equal(upcomingState.team,'DAL');assert.equal(upcomingState.game,expectedUpcoming,'Native upcoming link preserves its exact source fixture ID');assert.equal(linkedFixture?.id,expectedUpcoming,'Linked future fixture resolves from the reviewed matchup source');for(const field of['season','week','home_team','away_team'])assert.equal(linkedFixture[field],teamFixture[field],'Future linked fixture agrees with team source '+field);assert.equal(await page.locator(q.PAGE+' [data-mb-fixture]').getAttribute('data-mb-fixture'),expectedUpcoming,'Future destination header retains the actual selected game');r.upcomingEntry={state:upcomingState,fixtureId:expectedUpcoming,geometry:await q.geometry(page),quarterbacks:await q.genericQBSourceCheck(page,data,upcomingState)};await click(page.locator(q.PAGE+' .mb-back'),'Future matchup → originating Dallas');await q.active(page,'team-details');assert.match(page.url(),/#team\/DAL/);await page.goto(base+'#matchup/DAL',{waitUntil:'networkidle'});await q.ready(page);await q.active(page);await exact();const researchState=await page.evaluate(()=>window.MatchupBreakdown.getState()),researchFixture=model.fixture(data.matchup,'DAL',researchState);assert.equal(researchFixture?.id,data.matchup.teams.DAL.researchGameId||data.matchup.teams.DAL.upcomingGameId,'Direct route selects the explicit reviewed research fixture');assert.equal(await page.locator(q.PAGE+' [data-mb-fixture]').getAttribute('data-mb-fixture'),researchFixture.id);assert.deepEqual(new Set([researchFixture.home_team,researchFixture.away_team]),new Set(['DAL','TB']),'Approved current research matchup retains Dallas/Tampa Bay identity');r.researchEntry={state:researchState,fixtureId:researchFixture.id,quarterbacks:await q.genericQBSourceCheck(page,data,researchState)};r.geometry=await q.geometry(page);r.images=await q.images(page);r.scroll=await q.scrollEvidence(page,out,`matchup-${viewport.width}x${viewport.height}-hosted`);r.fullContent=await q.fullContent(page,out,`matchup-${viewport.width}x${viewport.height}-hosted`);
const leaders=await page.locator(q.PAGE+' [data-mb-leaders]').evaluateAll(es=>es.map(e=>({group:e.dataset.mbLeaders,ids:[...e.querySelectorAll('[data-mb-player-row]')].map(r=>r.dataset.mbPlayerRow)})));for(const group of leaders){const[abbr,kind]=group.group.split(':');assert.deepEqual(group.ids,model.leaders(data.matchup,abbr,kind,{window:5,season:'cross',venue:'all',mode:'total'}).map(r=>r.id),'Hosted source-ranked '+group.group);}r.leaders=leaders;
const player=page.locator(q.PAGE+' [data-mb-leaders="TB:receiving"] .mb-player-button').first(),id=await player.getAttribute('data-mb-player');await click(player,'Tampa Bay receiving player → actual game log');assert.equal((await page.evaluate(()=>window.MatchupBreakdown.getState())).player,'TB:'+id);await click(page.locator(q.PAGE+' [data-mb-player-detail] [data-mb-action="player-game"]').first(),'Selected player → game statistics');await page.locator('#matchup-breakdown-dialog').waitFor({state:'visible'});assert.ok((await page.locator('#matchup-dialog-content').innerText()).length>100);await close();
for(const action of['targets','routes','low']){await click(page.locator(q.PAGE+' .mb-player-insights [data-mb-action="'+action+'"]'),action+' insight');await page.locator('#matchup-breakdown-dialog').waitFor({state:'visible'});await close();}
await click(page.locator(q.PAGE+' [data-mb-qb="opponent"]'),'QB vs weekly opponent');assert.equal((await page.evaluate(()=>window.MatchupBreakdown.getState())).qb,'opponent');await click(page.locator(q.PAGE+' [data-mb-qb="last5"]'),'QB true last-five starts');
for(const tab of['form','lineup','players']){await click(page.locator(q.PAGE+' [data-mb-tab="'+tab+'"]'),'Actual '+tab+' panel');assert.equal(await page.locator('#matchup-panel-'+tab).isVisible(),true);r[tab+'Capture']=await q.capture(page,out,`matchup-${viewport.width}x${viewport.height}-${tab}-hosted`);await q.geometry(page);}
await page.selectOption('#matchup-window-select','3');await click(page.locator(q.PAGE+' [data-mb-mode="average"]'),'Actual per-game recomputation');const state=await page.evaluate(()=>window.MatchupBreakdown.getState());assert.equal(state.window,3);assert.equal(state.mode,'average');await page.reload({waitUntil:'networkidle'});await q.ready(page);await q.active(page);assert.equal((await page.evaluate(()=>window.MatchupBreakdown.getState())).window,3);await exact();r.directLoadReload=true;
await click(page.locator(q.PAGE+' [data-mb-action="sources"]').first(),'Source provenance');await page.locator('#matchup-breakdown-dialog').waitFor({state:'visible'});assert.ok(await page.locator('#matchup-dialog-content a[href^="https://"]').count());r.sourceDialog=await q.capture(page,out,`matchup-${viewport.width}x${viewport.height}-sources-hosted`);await close();
await page.evaluate(()=>{window.__hostedRefreshEvents=[];document.addEventListener('pd:matchup-data-ready',e=>window.__hostedRefreshEvents.push({type:'ready',...e.detail}));document.addEventListener('pd:matchup-data-error',e=>window.__hostedRefreshEvents.push({type:'error',...e.detail}));});const requestPromise=page.waitForResponse(s=>s.url().includes('/assets/data/matchup-breakdown.json'));await click(page.locator(q.PAGE+' [data-mb-action="refresh"]'),'Genuine hosted manual source revalidation');const request=await requestPromise;assert.ok([200,304].includes(request.status()));await page.waitForFunction(()=>window.__hostedRefreshEvents.length>0);const event=await page.evaluate(()=>window.__hostedRefreshEvents.at(-1));assert.equal(event.type,'ready');assert.equal(event.reason,'manual-or-source');await exact();r.actualManualRefresh={status:request.status(),event,sourceSubstitution:false};
await page.goto(base+'#matchup/DAL',{waitUntil:'networkidle'});await q.ready(page);await q.active(page);r.motion=await q.motion(page,base);await click(page.locator(q.PAGE+' .mb-back'),'Matchup → originating Dallas');await q.active(page,'team-details');assert.match(page.url(),/#team\/DAL/);await page.goto(base+'#nfl',{waitUntil:'networkidle'});await q.active(page,'nfl');const nflButton=page.locator('[data-page="nfl"] [data-nfl-action="matchup"]');if(await nflButton.count()){await click(nflButton,'NFL featured matchup → correct club/fixture');await q.ready(page);await q.active(page);assert.equal((await page.evaluate(()=>window.MatchupBreakdown.getState())).team,'PIT');await click(page.locator(q.PAGE+' .mb-back'),'Pittsburgh matchup → Pittsburgh form');await q.active(page,'team-details');assert.match(page.url(),/#team\/PIT/);}await page.goto(base+'#home',{waitUntil:'networkidle'});await q.active(page,'home');r.homeDiamond=await q.capture(page,out,`home-${viewport.width}x${viewport.height}-diamond-hosted`);await page.goto(base+'#matchup/DAL',{waitUntil:'networkidle'});await q.ready(page);await q.active(page);await exact();r.finalGeometry=await q.geometry(page);r.finalCapture=await q.capture(page,out,`matchup-${viewport.width}x${viewport.height}-final-hosted`);
const realFailures=failed.filter(f=>!['net::ERR_ABORTED','Load request cancelled'].includes(f.error));assert.deepEqual(errors,[]);assert.deepEqual(http,[]);assert.deepEqual(external,[]);assert.deepEqual(realFailures,[]);r.errors={javascriptAndConsole:errors,http,external,failed:realFailures};r.status='passed';r.completedAt=new Date().toISOString();}catch(e){r.status='failed';r.failure={message:e.message,stack:e.stack,errors,http,failed,external};try{r.failureCapture=await q.capture(page,out,'failure-'+viewport.width);}catch{}throw e;}finally{save();await context.close();}}
(async()=>{try{browser=await q.launch('webkit',true);report.browserVersion=browser.version();for(const viewport of[{width:393,height:852},{width:430,height:896},{width:1440,height:1000}]){await scenario(viewport);console.log('PASSED actual HTTPS '+viewport.width+'x'+viewport.height);}
const context=await browser.newContext(),page=await context.newPage();try{await page.goto(base+'#home',{waitUntil:'networkidle'});report.servedRuntime=await page.evaluate(async files=>{const rows=[];for(let i=0;i<files.length;i+=6)rows.push(...await Promise.all(files.slice(i,i+6).map(async file=>{const response=await fetch(file,{cache:'no-store'}),body=await response.arrayBuffer();return{file,status:response.status,bytes:body.byteLength,contentEncoding:response.headers.get('content-encoding'),contentLength:response.headers.get('content-length'),sha256:[...new Uint8Array(await crypto.subtle.digest('SHA-256',body))].map(v=>v.toString(16).padStart(2,'0')).join('')};})));return rows;},Object.keys(runtime));for(const row of report.servedRuntime){assert.equal(row.status,200,row.file+' genuine HTTPS200');assert.equal(row.sha256,runtime[row.file],row.file+' exact reviewed body');}const feed=report.servedRuntime.find(r=>r.file==='assets/data/matchup-breakdown.json');assert.ok(['gzip','br'].includes(feed.contentEncoding),'Host genuinely compresses large lazy-loaded matchup JSON');report.actualFeedCompression=feed;}finally{await context.close();}
assert.deepEqual(q.runtimeManifest(),runtime,'Application stayed frozen during actual hosted verification');assert.deepEqual(q.tests(),report.source.testFiles,'Native verification helpers stayed frozen');report.unchangedDuringQA=true;report.testLogicUnchangedDuringQA=true;report.status='passed';}catch(e){report.status='failed';report.failure={message:e.message,stack:e.stack};}finally{if(browser)await browser.close();report.completedAt=new Date().toISOString();save();console.log('Actual hosted evidence '+path.join(out,'results.json'));process.exitCode=report.status==='passed'?0:1;}})();
