'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),q=require('./qa.cjs'),m=require('./model.cjs');
const feed=q.sourceData().matchup,checks=[];function check(name,run){run();checks.push(name);}
check('Missing or incomplete numeric input cannot become zero',()=>{assert.equal(m.sum([]),null);assert.equal(m.sum([2,null,3]),null);assert.equal(m.sum([2,undefined]),null);assert.equal(m.sum([2,0,3]),5);});
check('Actual statistical-row GP is the per-game denominator',()=>{const total=m.leaders(feed,'DAL','rushing',{window:5,mode:'total'}),average=m.leaders(feed,'DAL','rushing',{window:5,mode:'average'}),p=total.find(r=>r.name==='Javonte Williams'),a=average.find(r=>r.id===p.id);assert.equal(p.values.GP,4);assert.equal(a.values.rushingYards,p.values.rushingYards/4);assert.notEqual(a.values.rushingYards,p.values.rushingYards/5);assert.equal(a.values.rushingYardsPerCarry,p.values.rushingYards/p.values.carries);});
check('Disputed target totals and dependent share remain null while verified yards may rank',()=>{const p=m.leaders(feed,'TB','receiving',{window:5,mode:'total'}).find(r=>/^Ted Hurst/.test(r.name));assert.ok(p);assert.equal(p.values.targets,null);assert.ok(p.values.receivingYards>0);});
check('Venue and current-season filtering precede newest-game limit',()=>{const current=m.games(feed,'DAL',{window:5,season:'current'}),cross=m.games(feed,'DAL',{window:5,season:'cross'}),away=m.games(feed,'DAL',{window:3,season:'cross',venue:'away'});assert.equal(current.length,4);assert.equal(cross.length,5);assert.equal(cross.at(-1).season,2025);assert.ok(away.every(g=>m.venue(g,'DAL')==='away'));assert.equal(away.length,3);});
check('Relief appearances cannot establish quarterback starts',()=>{const id=m.projectedQB(feed,'TB',m.fixture(feed,'DAL')).playerId,p=feed.teams.TB.players[id];assert.equal(p.gameLog.length,2);const rows=m.qbStarts(feed,'TB',id,{window:5});assert.equal(rows.length,1);assert.equal(rows[0].gameId,'2026_04_GB_TB');assert.equal(rows[0].started.status,'verified');});
check('QB personal opponent archive is unpadded and source confirmed',()=>{const id=m.projectedQB(feed,'DAL',m.fixture(feed,'DAL')).playerId,rows=m.qbStarts(feed,'DAL',id,{window:5,opponent:'TB'});assert.equal(rows.length,4);assert.ok(rows.every(r=>r.opponent==='TB'&&r.started.value===true));assert.deepEqual(rows.map(r=>r.season),[2022,2021,2018,2016]);});
check('Recent disputed QB candidates occupy their chronological window without older replacement',()=>{const records=Array.from({length:6},(_,i)=>({gameId:'synthetic-role-'+(6-i),season:2026,week:6-i,kickoffUtc:'2026-10-'+String(7-i).padStart(2,'0')+'T00:00:00Z',homeAway:'home',opponent:'TB',started:i===0?{candidate:true,value:null,status:'disputed'}:{candidate:true,value:true,status:'verified'},stats:{attempts:20,completions:10,passingYards:100,passingTD:1,interceptions:0}})),sample={season:2026,teams:{DAL:{players:{QB:{id:'QB',gameLog:records}}}}},window=m.qbWindow(sample,'DAL','QB',{window:5});assert.equal(window.candidates.length,5);assert.equal(window.confirmed.length,4);assert.equal(window.unresolvedRoles,1);assert.equal(window.rolesComplete,false);assert.ok(!window.confirmed.some(row=>row.gameId==='synthetic-role-1'),'An older sixth start cannot replace a disputed recent slot');assert.deepEqual(m.qbStarts(sample,'DAL','QB',{window:5}),window.confirmed);});
check('NFL passer rating is calculated from aggregate counts and explicit denominators',()=>{const rows=[{stats:{attempts:1,completions:1,passingYards:10,passingTD:1,interceptions:0}},{stats:{attempts:30,completions:15,passingYards:100,passingTD:0,interceptions:1}}];assert.ok(m.passerRating(rows)>0);assert.equal(m.passerRating([{stats:{attempts:0,completions:0,passingYards:0,passingTD:0,interceptions:0}}]),null);assert.equal(m.passerRating([{stats:{attempts:10,completions:null,passingYards:100,passingTD:1,interceptions:0}}]),null);});
check('Selected research and explicit upcoming fixture retain different source identities',()=>{const active={id:'live',season:2026,week:5,home_team:'DAL',away_team:'TB',status:'scheduled'},future={id:'future',season:2026,week:6,home_team:'DAL',away_team:'GB',status:'scheduled'},sample={season:2026,teams:{DAL:{games:[active,future],researchGameId:'live',upcomingGameId:'future',qbEvidence:{season:2026,week:5,playerId:'QB5',status:'verified'},fixtureReports:{live:{qbEvidence:{season:2026,week:5,playerId:'QB5',status:'verified'}},future:{qbEvidence:{status:'unavailable',playerId:null}}}}}};assert.equal(m.fixture(sample,'DAL').id,'live');assert.equal(m.fixture(sample,'DAL',{game:'future'}).id,'future');assert.equal(m.projectedQB(sample,'DAL',active).playerId,'QB5');assert.equal(m.projectedQB(sample,'DAL',future).playerId,null);delete sample.teams.DAL.fixtureReports.future;assert.equal(m.projectedQB(sample,'DAL',future).playerId,null,'A week5 bulletin cannot establish week6 projection');});
check('Source-reported in-progress game cannot enter completed team or QB windows',()=>{const active={id:'live',season:2026,week:5,home_team:'DAL',away_team:'TB',home_score:7,away_score:3,status:'final',seasonType:'REG',kickoffUtc:'2026-10-09T00:15:00Z'},past={...active,id:'past',week:4,kickoffUtc:'2026-10-02T00:15:00Z'},rows=[active,past].map(g=>({gameId:g.id,season:g.season,week:g.week,kickoffUtc:g.kickoffUtc,homeAway:'home',started:{candidate:true,value:true,status:'verified'},stats:{attempts:20}})),sample={season:2026,teams:{DAL:{games:[active,past],fixtureReports:{live:{eventStatus:{state:'in',completed:false}}},players:{QB:{gameLog:rows}}},TB:{}}};assert.equal(m.completed(sample,active),false,'Actual event status overrides final-looking schedule fields');assert.deepEqual(m.games(sample,'DAL',{window:5}).map(g=>g.id),['past']);assert.deepEqual(m.qbStarts(sample,'DAL','QB',{window:5}).map(r=>r.gameId),['past']);});
console.log(JSON.stringify({status:'passed',qualification:'Independent snapshot-specific real-source adverse-case expectations bound to this snapshot SHA, plus explicitly hypothetical QB candidate/rate/null unit inputs; app files untouched. Weekly hardcoded cases are not reusable freshness assertions.',snapshotSha256:q.SHA(fs.readFileSync(q.ROOT+'/assets/data/matchup-breakdown.json')),checks},null,2));
