'use strict';
// Independent QA expectations: no runtime implementation is imported.
const assert=require('node:assert/strict');
const isNumber=value=>typeof value==='number'&&Number.isFinite(value);
const sum=values=>values.length&&values.every(isNumber)?values.reduce((a,b)=>a+b,0):null;
const byNewest=(a,b)=>String(b.kickoffUtc||b.gameday||'').localeCompare(String(a.kickoffUtc||a.gameday||''))||Number(b.season)-Number(a.season)||Number(b.week)-Number(a.week)||String(b.id||b.gameId).localeCompare(String(a.id||a.gameId));
const isRegular=game=>!game.seasonType||['REG','regular','regular-season','2'].includes(String(game.seasonType));
const venue=(game,team)=>game.neutral===true?'neutral':game.neutral===false?(game.home_team===team?'home':'away'):'unknown';
function fixtureReport(data,game,abbr){return game?data.teams[abbr]?.fixtureReports?.[game.id]||null:null;}
function completed(data,game){const report=fixtureReport(data,game,game.home_team)||fixtureReport(data,game,game.away_team);return game.status==='final'&&isNumber(game.home_score)&&isNumber(game.away_score)&&report?.eventStatus?.state!=='in';}
function fixture(data,abbr,state={}){const club=data.teams[abbr];assert.ok(club);for(const id of[state.game,club.researchGameId,club.upcomingGameId]){const game=club.games.find(g=>g.id===id);if(game)return game;}return club.games.filter(g=>Number(g.season)===Number(data.season)&&!completed(data,g)&&!['cancelled','postponed'].includes(g.status)).sort((a,b)=>String(a.kickoffUtc||a.gameday||'').localeCompare(String(b.kickoffUtc||b.gameday||'')))[0]||null;}
function projectedQB(data,abbr,game){const report=fixtureReport(data,game,abbr);if(report?.qbEvidence)return report.qbEvidence;const evidence=data.teams[abbr]?.qbEvidence;return evidence&&game&&Number(evidence.season)===Number(game.season)&&Number(evidence.week)===Number(game.week)?evidence:{status:'unavailable',playerId:null};}
function completedLog(data,abbr,row){const game=data.teams[abbr]?.games?.find(g=>g.id===row.gameId);return !game||completed(data,game);}
function games(data,abbr,options={}){const club=data.teams[abbr];assert.ok(club,'Sourced club exists: '+abbr);return club.games.filter(g=>completed(data,g)&&isRegular(g)&&g.season<=data.season&&(!options.season||options.season==='cross'||g.season===data.season)&&(!options.venue||options.venue==='all'||venue(g,abbr)===options.venue)).sort(byNewest).slice(0,Number(options.window||5));}
function actualRows(player,team,selection){const ids=new Set(selection.map(g=>String(g.id)));return(player.gameLog||[]).filter(row=>ids.has(String(row.gameId))&&row.team===team&&!['DNP','dnp','inactive'].includes(row.appearance?.status)&&row.appearance?.value!==false&&(row.appearance?.status==='verified'||Object.values(row.stats||{}).some(isNumber))).sort((a,b)=>byNewest({...a,id:a.gameId},{...b,id:b.gameId}));}
function field(rows,name,mode='total',divisor=rows.length){const value=sum(rows.map(row=>row.stats?.[name]));return value===null?null:mode==='average'?(divisor>0?value/divisor:null):value;}
function leaders(data,abbr,kind,options={}){const selected=games(data,abbr,options),yardKey=kind==='rushing'?'rushingYards':'receivingYards',volumeKey=kind==='rushing'?'carries':'receptions',results=[];for(const player of Object.values(data.teams[abbr].players||{})){const rows=actualRows(player,abbr,selected),yards=field(rows,yardKey),volume=field(rows,volumeKey);if(!rows.length||yards===null||(kind==='rushing'?(volume===null||volume<=0):!((field(rows,'targets')??0)>0||(volume??0)>0)))continue;const gp=rows.filter(row=>Object.values(row.stats||{}).some(isNumber)).length,perGame=name=>field(rows,name,options.mode,gp),values=kind==='rushing'?{GP:gp,carries:perGame('carries'),rushingYards:perGame('rushingYards'),rushingYardsPerCarry:volume?yards/volume:null,rushingTD:perGame('rushingTD')}:{GP:gp,targets:perGame('targets'),receptions:perGame('receptions'),receivingYards:perGame('receivingYards'),receivingTD:perGame('receivingTD')};results.push({id:player.id,name:player.name,rankYards:yards,rows:rows.map(r=>r.gameId),values});}return results.sort((a,b)=>b.rankYards-a.rankYards||a.name.localeCompare(b.name)).slice(0,5);}
function qbWindow(data,abbr,id,options={}){const player=data.teams[abbr].players[id];assert.ok(player);const candidates=(player.gameLog||[]).filter(row=>completedLog(data,abbr,row)&&(row.started?.candidate===true||row.started?.value===true)&&isRegular(row)&&row.season<=data.season&&(!options.season||options.season==='cross'||row.season===data.season)&&(!options.opponent||row.opponent===options.opponent)&&(!options.venue||options.venue==='all'||row.homeAway===options.venue)).sort((a,b)=>byNewest({...a,id:a.gameId},{...b,id:b.gameId})).slice(0,Number(options.window||5));const confirmed=candidates.filter(row=>row.started?.value===true&&row.started?.status==='verified');return{candidates,confirmed,unresolvedRoles:candidates.length-confirmed.length,rolesComplete:candidates.length>0&&confirmed.length===candidates.length};}
function qbStarts(data,abbr,id,options={}){return qbWindow(data,abbr,id,options).confirmed;}
function passerRating(rows){const attempts=field(rows,'attempts'),completions=field(rows,'completions'),yards=field(rows,'passingYards'),td=field(rows,'passingTD'),ints=field(rows,'interceptions');if([attempts,completions,yards,td,ints].some(v=>v===null)||attempts<=0)return null;const clamp=v=>Math.max(0,Math.min(2.375,v));return(clamp((completions/attempts-.3)*5)+clamp((yards/attempts-3)*.25)+clamp(td/attempts*20)+clamp(2.375-ints/attempts*25))/6*100;}
function textNumber(text){const normalized=String(text).trim().replace(/,/g,'').replace(/[−–]/g,'-');if(/^(?:—|-|N\/A|Unavailable|Pending)$/i.test(normalized))return null;const match=normalized.match(/^[+-]?\d+(?:\.\d+)?/);return match?Number(match[0]):null;}
function matchNumber(actual,expected,label,tolerance=.051){const value=textNumber(actual);if(expected===null)assert.equal(value,null,label+': missing values remain unavailable');else assert.ok(value!==null&&Math.abs(value-expected)<=tolerance,label+': rendered '+JSON.stringify(actual)+' must equal '+expected);}
module.exports={isNumber,sum,byNewest,isRegular,venue,fixtureReport,completed,fixture,projectedQB,completedLog,games,actualRows,field,leaders,qbWindow,qbStarts,passerRating,textNumber,matchNumber};
