'use strict';
const assert=require('node:assert/strict');
const {NFL,active,geometry}=require('./qa.cjs');
const fmt=v=>v===null||v===undefined||v===''||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString('en-US');
const abbr=t=>t.abbr||t.id.toUpperCase();
function allFinals(data,week){const games=new Map();for(const s of Object.values(data.weeks))for(const g of s.recap||[])if(g.id&&g.status==='final'&&g.season===data.season&&Number(g.week)<=week)games.set(g.id,g);return[...games.values()].sort((a,b)=>a.week-b.week||a.gameday.localeCompare(b.gameday)||a.id.localeCompare(b.id));}
function results(data,through,t){const code=abbr(t),games=allFinals(data,through).filter(g=>g.home_team===code||g.away_team===code);if(games.length!==Number(t.w)+Number(t.l)+Number(t.ties||0))return null;const list=games.map(g=>{const h=g.home_team===code,own=h?g.home_score:g.away_score,other=h?g.away_score:g.home_score;return{result:own>other?'W':own<other?'L':'T',own,other,home:h};});if(list.filter(x=>x.result==='W').length!==t.w||list.filter(x=>x.result==='L').length!==t.l||list.reduce((s,x)=>s+x.own,0)!==t.pointsFor||list.reduce((s,x)=>s+x.other,0)!==t.pointsAgainst)return null;return list;}
async function rows(page,data,week,conf,division='all',sort='PCT',form=4){const source=data.weeks[week],all=source.conferences[conf]||[],teamMap=new Map(data.teams.map(t=>[t.abbr,t]));const dom=await page.locator('#standings-rows .stand-row').evaluateAll(rs=>rs.map(r=>({abbr:r.querySelector('[data-team]').dataset.team,cells:[...r.querySelectorAll(':scope > [role=cell]')].map(x=>x.innerText.trim()),form:[...r.querySelectorAll('.form-chip')].map(x=>x.textContent)})));assert.ok(dom.length>0,'Standings show verified teams');const filtered=all.filter(t=>division==='all'||teamMap.get(abbr(t)).division===division);if(await page.locator('[data-standings-toggle]').getAttribute('aria-expanded')==='false')assert.equal(dom.length,Math.min(5,filtered.length),'Compact conference consistently shows five source-backed rows when available');const context={PCT:{label:'win percentage',index:4,direction:'descending'},PF:{label:'points scored',index:5,direction:'descending'},PA:{label:'points allowed',index:6,direction:'ascending'},DIFF:{label:'point differential',index:7,direction:'descending'}}[sort];assert.match(await page.locator(NFL+' .standings').getAttribute('aria-label'),new RegExp(context.label));const headings=await page.locator(NFL+' [role=columnheader]').evaluateAll(h=>h.map((x,i)=>({index:i,sort:x.getAttribute('aria-sort'),highlight:x.classList.contains('nfl-sort-heading')})));assert.deepEqual(headings.filter(x=>x.sort||x.highlight),[{index:context.index,sort:context.direction,highlight:true}],'Sort accessibility direction/header highlights match actual selected metric');const metric=t=>sort==='PF'?t.pointsFor:sort==='PA'?-t.pointsAgainst:sort==='DIFF'?t.pointDifferential:Number(t.pct);let prev=Infinity;for(const r of dom){const t=all.find(t=>abbr(t)===r.abbr);assert.ok(t,`Row ${r.abbr} exists in selected verified conference`);assert.ok(division==='all'||teamMap.get(r.abbr).division===division,'Division filters accurately');assert.equal(r.cells.length,9,'Dense table has all nine aligned columns');assert.equal(r.cells[1],t.name);assert.equal(r.cells[2],fmt(t.w));assert.equal(r.cells[3],fmt(t.l)+(t.ties?`+${t.ties}T`:''));assert.equal(r.cells[4],t.pct);assert.equal(r.cells[5],fmt(t.pointsFor));assert.equal(r.cells[6],fmt(t.pointsAgainst));const d=t.pointDifferential??t.pointsFor-t.pointsAgainst;assert.equal(r.cells[7],(d>0?'+':'')+fmt(d));assert.ok(metric(t)<=prev,'Source metrics are monotonically sorted');prev=metric(t);const rs=results(data,source.throughWeek,t);assert.deepEqual(r.form,rs?rs.slice(-form).map(x=>x.result):[],'Recent form is exact complete final-score history or unavailable');}return{rows:dom,season:data.season,week,throughWeek:source.throughWeek,conf,division,sort,form};}
// The source abbreviation is preserved; only a missing space after its initial
// prefix is added for display. Verify independently using prefix positions.
function displayName(player) {
  const raw = player.short || player.name;
  const dot = raw.indexOf('.');
  return dot >= 1 && dot <= 3 && /^[A-Za-z]+$/.test(raw.slice(0,dot)) && raw[dot+1] && !/\s/.test(raw[dot+1])
    ? raw.slice(0,dot+1) + ' ' + raw.slice(dot+1) : raw;
}
async function leaders(page,data,week) {
  const snapshots=[];
  for(const position of ['QB','RB','WR']) {
    const panel=page.locator(`.page.active [data-nfl-leader-panel="${position}"]:visible`).first();
    assert.equal(await panel.count(),1,`Current tab has ${position} panel`);
    const expected=data.weeks[week].leaders?.[position]||[];
    async function compare(source) {
      const actual=await panel.locator('.leader-row').evaluateAll(rs=>rs.map(r=>({rank:r.querySelector('b').textContent,name:r.querySelectorAll('span')[0].textContent,fullName:r.querySelectorAll('span')[0].getAttribute('title'),yards:r.querySelectorAll('span')[1].textContent,td:r.querySelectorAll('span')[2].textContent})));
      assert.deepEqual(actual,source.map((p,i)=>({rank:String(i+1),name:displayName(p),fullName:p.name,yards:fmt(p.yards),td:fmt(p.td)})),`Exact ${position} source names, full-name titles and statistics`);
      for(let i=0;i<actual.length;i++) assert.equal(actual[i].name.replace(/\s/g,''),(source[i].short||source[i].name).replace(/\s/g,''),'Display spacing never changes the source name characters');
      return actual;
    }
    const compact=await compare(expected.slice(0,5));
    await panel.locator('[data-nfl-action="leaders"]').click();await active(page,'nfl');
    assert.equal(await panel.locator('[data-nfl-action="leaders"]').getAttribute('aria-expanded'),'true');
    assert.equal(await panel.locator('.leader-row').count(),expected.length,'View all never invents additional leaders');
    const expanded=await compare(expected);
    await panel.locator('[data-nfl-action="leaders"]').click();
    assert.equal(await panel.locator('[data-nfl-action="leaders"]').getAttribute('aria-expanded'),'false');
    snapshots.push({position,comparedRecords:compact.length,expandedRecords:expanded.length});
  }
  return snapshots;
}
async function preview(page,action){const b=page.locator(`${NFL} [data-nfl-action="${action}"]:visible`).first();assert.equal(await b.isEnabled(),true,`${action} control is enabled`);await b.scrollIntoViewIfNeeded();await b.click();await active(page,'nfl');assert.match(page.url(),/#nfl$/,'Deferred destination stays on NFL route');const p=page.locator('#nfl-inline-preview');await p.waitFor({state:'visible'});assert.equal(await p.evaluate(e=>e===document.activeElement),true,'Preview receives keyboard focus');const title=await p.locator('h2').innerText(),text=await p.innerText();assert.ok(text.length>30,'Deferred destination responds with useful in-place feedback');assert.doesNotMatch(text,/later pass|current build focus|connected in a later|preview only/i,'Future destinations use product wording');await p.locator('[data-nfl-action="close-preview"]').click();await p.waitFor({state:'hidden'});return{action,title,text};}
async function controls(page,base,data,full=false){const evidence={};await page.locator(NFL+' [data-nfl-tab="ladder"]').click();await page.locator('#week-select').selectOption(String(data.currentWeek));for(const conference of ['NFC','AFC']){await page.locator(`[data-conference="${conference}"]`).click();assert.equal(await page.locator(`[data-conference="${conference}"]`).getAttribute('aria-pressed'),'true');evidence[conference]=await rows(page,data,data.currentWeek,conference);}
 const options=await page.locator('#division-select option').evaluateAll(o=>o.map(x=>x.value));evidence.divisions=[];for(const division of options){await page.locator('#division-select').selectOption(division);evidence.divisions.push(await rows(page,data,data.currentWeek,'AFC',division));}await page.locator('#division-select').selectOption('all');
 evidence.sorts=[];for(const sort of ['PF','PA','DIFF','PCT']){await page.locator('#standings-sort').selectOption(sort);evidence.sorts.push(await rows(page,data,data.currentWeek,'AFC','all',sort));}
 for(const form of [5,4]){await page.locator('#form-select').selectOption(String(form));await rows(page,data,data.currentWeek,'AFC','all','PCT',form);}
 await page.locator('[data-standings-toggle]').click();assert.equal(await page.locator('[data-standings-toggle]').getAttribute('aria-expanded'),'true');assert.equal(await page.locator('#standings-rows .stand-row').count(),data.weeks[data.currentWeek].conferences.AFC.length,'All conference rows exposed');await geometry(page);
 const teams=await page.locator('#standings-rows [data-nfl-action="team"]').evaluateAll(bs=>bs.map(b=>b.dataset.team));evidence.teamSummaries=[];for(const team of (full?teams:teams.slice(0,2))){const b=page.locator(`[data-nfl-action="team"][data-team="${team}"]`);if(await b.getAttribute('aria-expanded')==='true')await b.click();await b.click();assert.equal(await b.getAttribute('aria-expanded'),'true');assert.equal(await page.locator('.nfl-team-summary').count(),1);await active(page,'nfl');assert.match(page.url(),/#nfl$/);const metric=await page.locator('.nfl-summary-metric').evaluateAll(xs=>xs.map(x=>[x.querySelector('small').textContent,x.querySelector('strong').textContent]));const source=data.weeks[data.currentWeek].conferences.AFC.find(t=>abbr(t)===team);assert.equal(metric[0][1],fmt(source.pointsFor));assert.equal(metric[1][1],fmt(source.pointsAgainst));evidence.teamSummaries.push({team,metric});await b.click();assert.equal(await b.getAttribute('aria-expanded'),'false');}
 await page.locator('[data-standings-toggle]').click();assert.equal(await page.locator('[data-standings-toggle]').getAttribute('aria-expanded'),'false');const pit=page.locator('[data-nfl-action="team"][data-team="PIT"]');if(await pit.getAttribute('aria-expanded')==='false')await pit.click();evidence.preview=[];evidence.preview.push(await preview(page,'team-details'));
 for(const tab of ['players','recap','ladder']){await page.locator(`[data-nfl-tab="${tab}"]`).click();assert.equal(await page.locator('#panel-'+tab).isVisible(),true,'Tabs switch correct panel');assert.equal(await page.locator(`[data-nfl-tab="${tab}"]`).getAttribute('aria-selected'),'true');if(tab==='players')evidence.playerLeaders=await leaders(page,data,data.currentWeek);}
 await page.locator('[data-nfl-tab="ladder"]').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('[data-nfl-tab="players"]').getAttribute('aria-selected'),'true');await page.keyboard.press('End');assert.equal(await page.locator('[data-nfl-tab="recap"]').getAttribute('aria-selected'),'true');await page.keyboard.press('Home');assert.equal(await page.locator('[data-nfl-tab="ladder"]').getAttribute('aria-selected'),'true');
 evidence.leaders=await leaders(page,data,data.currentWeek);for(const action of ['matchup','compare','team-form','teams','matchups','insights','more'])evidence.preview.push(await preview(page,action));
 const weeks=await page.locator('#week-select option').evaluateAll(o=>o.map(x=>x.value));evidence.weeks=[];for(const week of (full?weeks:[weeks[0],String(data.currentWeek),weeks.at(-1)])){await page.locator('#week-select').selectOption(week);await rows(page,data,week,'AFC');const fixture=data.weeks[week].fixture,text=await page.locator('#featured-matchup').innerText();if(fixture){const opponent=fixture.home_team==='PIT'?fixture.away_team:fixture.home_team;const name=data.teams.find(t=>t.abbr===opponent)?.name||data.teamNames?.[opponent]||opponent;assert.ok(text.includes(name.toUpperCase())||text.includes(name),'Selected fixture opponent matches source');}else assert.match(text,/No Steelers fixture/);assert.match(await page.locator('#fixture-context').innerText(),new RegExp(`WEEK ${week}$`));await geometry(page);evidence.weeks.push({week,fixture:fixture?.id||null});}await page.locator('#week-select').selectOption(String(data.currentWeek));
 await page.locator(NFL+' [data-sources]').first().click();await page.locator('#sources-dialog').waitFor({state:'visible'});assert.match(await page.locator('#sources-dialog').innerText(),/Retrieved|Retrieved|retrieved|Checked/);await page.keyboard.press('Escape');assert.equal(await page.locator('#sources-dialog').isVisible(),false);
 await page.locator(NFL+' .page-scroll').evaluate(e=>e.scrollTop=0);return evidence;}
module.exports={controls,rows,results};
