'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{spawn,execFileSync}=require('node:child_process'),{once}=require('node:events');
const {ROOT,NFL,launch,runtimeManifest,SHA,WAIT,ready,active,geometry,images,capture,scrollEvidence,fullContent,freePort}=require('./qa.cjs');
const {rows}=require('./controls.cjs'),{native}=require('./motion.cjs');
const args=process.argv.slice(2),arg=n=>{const i=args.indexOf(n);return i<0?null:args[i+1];},engine=arg('--engine'),name=arg('--run-name'),expectedFreeze=arg('--freeze');assert.ok(['chromium','webkit'].includes(engine));assert.match(name||'',/^[a-zA-Z0-9_-]+$/);assert.match(expectedFreeze||'',/^[a-f0-9]{64}$/);
const out=path.join(__dirname,name+'-'+engine);assert.ok(!fs.existsSync(out),'Never overwrite saved QA');fs.mkdirSync(out,{recursive:true});const frozenPath=arg('--manifest')||path.join(ROOT,'qa/nfl-diamond/runtime-manifest.json'),frozen=fs.readFileSync(frozenPath),manifest=runtimeManifest();assert.equal(SHA(frozen),expectedFreeze);assert.deepEqual(manifest,JSON.parse(frozen));assert.equal(Object.keys(manifest).length,203);fs.writeFileSync(out+'/runtime-manifest.json',frozen);
const dataBytes=fs.readFileSync(ROOT+'/assets/data/current.json'),data=JSON.parse(dataBytes),old=JSON.parse(fs.readFileSync(arg('--previous-manifest')||path.join(ROOT,'qa/nfl-diamond/approved-runtime-manifest.json')));const diff=Object.keys(manifest).filter(k=>manifest[k]!==old[k]);assert.deepEqual(diff.sort(),['assets/data/current.json','assets/data/player-history.json','assets/data/provenance.json'],'Metadata integration preserves all 200 non-data runtime files');const report={status:'running',engine,startedAt:new Date().toISOString(),source:{gitHead:execFileSync('git',['rev-parse','HEAD'],{cwd:ROOT,encoding:'utf8'}).trim(),runtimeFiles:manifest,frozenManifestSha256:expectedFreeze,snapshotHash:SHA(dataBytes)},qualification:{genuineNativeBrowsers:true,deviceScaleFactor:2,physicalIPhone:false,responseOrDataSubstitution:false,scope:'Targeted integration after independently proved metadata-only upstream changes. Prior complete 96db application/visual/regression suites remain immutable; this check does not repeat those broader tests.'},integratedData:{retrievedAt:data.retrievedAt,rosterCount:data.roster.length,currentWeek:data.currentWeek,nonDataFilesUnchanged:200,changedFiles:diff},results:[]};let browser,server,base;
async function settled(p){await images(p);await p.evaluate(async()=>{await Promise.all([...document.querySelectorAll('.page.active img')].filter(i=>i.checkVisibility()).map(i=>i.decode?.().catch(()=>{})));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});}
async function leaderValues(p){return p.locator(NFL+' #ladder-leaders [data-nfl-leader-panel]').evaluateAll(ps=>ps.map(panel=>({position:panel.dataset.nflLeaderPanel,rows:[...panel.querySelectorAll('.leader-row')].map(r=>({rank:r.querySelector('b').textContent,name:r.querySelectorAll('span')[0].textContent,yards:r.querySelectorAll('span')[1].textContent,td:r.querySelectorAll('span')[2].textContent}))})));}
const fmt=v=>v===null||v===undefined||v===''||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString('en-US');
function checkLeaders(records){assert.equal(records.length,3);for(const x of records){const src=data.weeks[data.currentWeek].leaders[x.position]||[];assert.equal(src.length,16,'Retains all 16 source-backed leaders for every current position');assert.deepEqual(x.rows,src.slice(0,5).map((r,i)=>({rank:String(i+1),name:r.short||r.name,yards:fmt(r.yards),td:fmt(r.td)})));}}
async function testcase(viewport){const context=await browser.newContext({viewport,deviceScaleFactor:2,isMobile:true,hasTouch:true,timezoneId:'Australia/Sydney'}),p=await context.newPage(),result={viewport,status:'running'},errors=[],http=[],failed=[],external=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});p.on('response',r=>{if(r.status()>=400)http.push({url:r.url(),status:r.status()});});p.on('requestfailed',r=>failed.push({url:r.url(),message:r.failure()?.errorText}));await p.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin===new URL(base).origin||['data:','blob:','about:'].includes(u.protocol))return route.continue();external.push(u.href);return route.abort();});
try{assert.equal((await p.goto(base+'#home',{waitUntil:'networkidle'})).status(),200);await ready(p);await active(p,'home');result.homeShell=await p.locator('.page.active').boundingBox();await p.locator('[data-home-entry]').tap();await active(p,'nfl');await settled(p);assert.deepEqual(await p.evaluate(()=>window.PD_DATA),data);assert.match(await p.locator('script[src*="assets/app.js"]').getAttribute('src'),/\?v=diamond20261008$/);result.geometry=await geometry(p);assert.ok(Math.abs(result.geometry.page.width-result.homeShell.width)<1&&Math.abs(result.geometry.page.height-result.homeShell.height)<1);assert.deepEqual(result.geometry.clipped,[]);result.images=await images(p);const label=`integration-${engine}-${viewport.width}x${viewport.height}`;result.top=await capture(p,out,label+'-top');
result.nativeFirst=await native(p);await p.waitForTimeout(300);result.nativeSecond=await native(p);assert.equal(result.nativeFirst.state,'running');assert.ok(result.nativeSecond.clocks.some((c,i)=>c.state==='running'&&Number(c.time)>Number(result.nativeFirst.clocks[i]?.time??0)),'Actual native light clock advances after metadata integration');for(const t of result.nativeSecond.text){assert.equal(t.transform,'none');assert.equal(t.animation,'none');}
result.compactRecords=await rows(p,data,data.currentWeek,'AFC');result.leaders=await leaderValues(p);checkLeaders(result.leaders);await p.locator('[data-standings-toggle]').click();result.allCurrentRecords=await rows(p,data,data.currentWeek,'AFC');assert.equal(result.allCurrentRecords.rows.length,data.weeks[data.currentWeek].conferences.AFC.length);await p.locator('[data-standings-toggle]').click();
const oldStatus=await p.evaluate(()=>window.PD_UPDATE_STATUS),responsePromise=p.waitForResponse(r=>new URL(r.url()).pathname.endsWith('/assets/data/current.json')&&r.request().method()==='GET');const refresh=p.locator(NFL+' [data-refresh]');await refresh.focus();await refresh.click();const response=await responsePromise;assert.equal(response.status(),200,'Actual native manual refresh returns same-origin HTTP200');await response.finished();const bytes=await response.body();assert.equal(SHA(bytes),manifest['assets/data/current.json'],'Refresh body is the exact frozen integrated snapshot');await p.waitForFunction(oldCheck=>window.PD_UPDATE_STATUS?.reason==='manual'&&window.PD_UPDATE_STATUS.state==='unchanged'&&window.PD_UPDATE_STATUS.lastCheckedAt!==oldCheck,oldStatus.lastCheckedAt);assert.deepEqual(await p.evaluate(()=>window.PD_DATA),data);assert.equal(await p.evaluate(()=>document.activeElement?.matches('[data-refresh]')),true,'Actual refresh preserves focused native refresh control');result.manualRefresh={url:response.url(),httpStatus:response.status(),sha256:SHA(bytes),status:await p.evaluate(()=>window.PD_UPDATE_STATUS),focusPreserved:true};assert.equal(result.manualRefresh.status.sourceRetrievedAt,data.retrievedAt);assert.match(await p.locator('#data-status').getAttribute('title'),/Automatically checked/);
await p.locator(NFL+' #data-status [data-sources]').click();await p.locator('#sources-dialog').waitFor({state:'visible'});const expectedTime=await p.evaluate(t=>new Date(t).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'}),data.retrievedAt);result.sourceDialog=await p.locator('#sources-content').innerText();assert.ok(result.sourceDialog.includes('Retrieved '+expectedTime),'Sources dialog shows exact integrated retrieval time');await p.keyboard.press('Escape');assert.equal(await p.locator('#sources-dialog').isVisible(),false);
await p.reload({waitUntil:'networkidle'});await ready(p);await active(p,'nfl');await settled(p);assert.deepEqual(await p.evaluate(()=>window.PD_DATA),data);result.directReload=true;result.reloadedGeometry=await geometry(p);assert.deepEqual(result.reloadedGeometry.clipped,[]);result.reloadedLeaders=await leaderValues(p);checkLeaders(result.reloadedLeaders);result.reloadedRecords=await rows(p,data,data.currentWeek,'AFC');result.scroll=await scrollEvidence(p,out,label);result.full=await fullContent(p,out,label);await settled(p);result.final=await capture(p,out,label+'-final');result.errors={javascriptAndConsole:errors,http,external,failed:failed.filter(x=>!['net::ERR_ABORTED','Load request cancelled'].includes(x.message)),cancelledNavigations:failed.filter(x=>['net::ERR_ABORTED','Load request cancelled'].includes(x.message))};for(const key of ['javascriptAndConsole','http','external','failed'])assert.deepEqual(result.errors[key],[]);result.status='passed';return result;
}catch(e){result.status='failed';result.failure={message:e.message,stack:e.stack,errors,http,failed,external};try{await p.screenshot({path:out+'/failure-'+viewport.width+'.png'});}catch{}return result;}finally{await context.close();}}
(async()=>{try{const port=await freePort();base=`http://127.0.0.1:${port}/${encodeURIComponent(path.basename(ROOT))}/`;report.base=base;server=spawn('python3',['-u','-m','http.server',String(port),'--bind','127.0.0.1','--directory',path.dirname(ROOT)],{stdio:'ignore'});await WAIT(200);browser=await launch(engine);report.browserVersion=browser.version();for(const v of[{width:393,height:852},{width:430,height:896}]){const r=await testcase(v);report.results.push(r);fs.writeFileSync(out+'/results.json',JSON.stringify(report,null,2));console.log(engine+' '+v.width+' '+r.status+(r.failure?' '+r.failure.message:''));}report.unchangedDuringQA=JSON.stringify(runtimeManifest())===JSON.stringify(manifest);assert.ok(report.unchangedDuringQA);report.status=report.results.every(r=>r.status==='passed')?'passed':'failed';}catch(e){report.status='failed';report.failure={message:e.message,stack:e.stack};}finally{report.completedAt=new Date().toISOString();fs.writeFileSync(out+'/results.json',JSON.stringify(report,null,2));if(browser)await browser.close();if(server){server.kill('SIGTERM');if(server.exitCode===null)await once(server,'exit');}console.log(out+'/results.json');process.exitCode=report.status==='passed'?0:1;}})();
