'use strict';
const assert=require('node:assert/strict');
const {NFL,active,ready}=require('./qa.cjs');
async function native(page){return page.locator(NFL).evaluate(n=>({state:n.dataset.nflMotionState,reason:n.dataset.nflMotionReason,zones:[...n.querySelectorAll('.nfl-motion-zone')].map((z,i)=>({i,visible:z.dataset.nflMotionVisibility,label:z.getAttribute('aria-label')||z.className})),clocks:n.getAnimations({subtree:true}).filter(a=>(a.animationName||'').startsWith('nfl-')&&a.effect?.getComputedTiming().iterations===Infinity).map(a=>({name:a.animationName,state:a.playState,time:a.currentTime,target:a.effect.target?.className,pseudo:a.effect.pseudoElement||null,zone:a.effect.target?.closest('.nfl-motion-zone')?.dataset.nflMotionVisibility||null})),text:[...n.querySelectorAll('.stand-row,.leader-row')].map(e=>({transform:getComputedStyle(e).transform,animation:getComputedStyle(e).animationName}))}));}
async function motion(page,base){
 await page.locator(NFL+' .page-scroll').evaluate(s=>s.scrollTop=0);await page.waitForFunction(()=>document.querySelector('.page[data-page="nfl"]').dataset.nflMotionState==='running');await page.waitForTimeout(180);
 const first=await native(page);await page.waitForTimeout(360);const second=await native(page);assert.equal(first.state,'running');assert.ok(first.clocks.some(c=>c.state==='running'),'Native decorative clocks run');assert.ok(second.clocks.some((c,i)=>c.state==='running'&&c.time!==first.clocks[i]?.time),'Native decorative clock time advances without seeking');for(const t of second.text){assert.equal(t.transform,'none','Factual table text remains stationary');assert.equal(t.animation,'none','No factual-row animation');}
 for(const c of second.clocks)if(c.zone==='out')assert.equal(c.state,'paused',`Offscreen light ${c.name} paused natively`);
 await page.locator(NFL+' .page-scroll').evaluate(s=>s.scrollTop=s.scrollHeight);await page.waitForTimeout(200);const bottom=await native(page);assert.ok(bottom.zones.some(z=>z.visible==='out'),'Top panels genuinely leave scroller viewport');for(const c of bottom.clocks)if(c.zone==='out')assert.equal(c.state,'paused',`Internal scroll pauses native clock ${c.name}`);assert.ok(bottom.clocks.some(c=>c.zone==='in'&&c.state==='running'),'Visible lower panel lighting still runs');
 await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>document.querySelector('.page[data-page="nfl"]').dataset.nflMotionState==='reduced');const reduced=await native(page);assert.equal(reduced.clocks.filter(c=>c.state==='running').length,0,'Reduced motion has no active native infinite clocks');await page.waitForTimeout(150);const still=await native(page);assert.deepEqual(still.clocks,reduced.clocks,'Reduced-motion clocks remain still');await page.emulateMedia({reducedMotion:'no-preference'});await page.waitForFunction(()=>document.querySelector('.page[data-page="nfl"]').dataset.nflMotionState==='running');
 await page.locator(NFL+' [data-open="home"]').click();await active(page,'home');await page.waitForFunction(()=>document.querySelector('.page[data-page="nfl"]').dataset.nflMotionState==='paused');const inactive=await native(page);assert.equal(inactive.reason,'inactive');assert.equal(inactive.clocks.filter(c=>c.state==='running').length,0,'Inactive route runs no native NFL clocks');await page.locator('[data-home-select="nfl"]').click();await page.locator('[data-home-entry]').click();await active(page,'nfl');await page.waitForFunction(()=>document.querySelector('.page[data-page="nfl"]').dataset.nflMotionState==='running');const resumed=await native(page);assert.ok(resumed.clocks.some(c=>c.state==='running'),'NFL native clocks resume on route return');
 await page.evaluate(()=>window.addEventListener('pagehide',()=>{const n=document.querySelector('.page[data-page="nfl"]');sessionStorage.setItem('__nfl_qa_pagehide',JSON.stringify({state:n.dataset.nflMotionState,reason:n.dataset.nflMotionReason,running:n.getAnimations({subtree:true}).filter(a=>(a.animationName||'').startsWith('nfl-')&&a.playState==='running').length}));}));await page.goto('about:blank');await page.goBack({waitUntil:'networkidle'});await ready(page);await active(page,'nfl');const pagehide=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('__nfl_qa_pagehide')));assert.equal(pagehide.state,'paused');assert.equal(pagehide.reason,'pagehide');assert.equal(pagehide.running,0,'Genuine document departure pauses all NFL clocks');await page.waitForFunction(()=>document.querySelector('.page[data-page="nfl"]').dataset.nflMotionState==='running');
 return{first,second,bottom,reduced,inactive,resumed,pagehide,naturalNativeTimeVerified:true,physicalIPhoneFPS:false,qualification:'Native route changes, inner-scroller intersections, reduced-motion media and actual document departure/back. Browser background-tab visibility is not claimed as physical iPhone behavior.'};
}
module.exports={motion,native};
