'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const {spawn,execFileSync}=require('node:child_process');
const {once}=require('node:events');
const net=require('node:net');
const ROOT=path.resolve(__dirname,'../..');
const {launch,runtimeManifest}=require(ROOT+'/qa/home-gate.cjs');
const SHA=b=>crypto.createHash('sha256').update(b).digest('hex');
const NFL='.page[data-page="nfl"]';
const OUT=__dirname;
const WAIT=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function ready(page){await page.waitForFunction(()=>document.documentElement.dataset.dataReady==='true'&&window.PD_DATA?.roster?.length);await page.evaluate(async()=>document.fonts.ready);}
async function active(page,id){await page.waitForFunction(value=>document.querySelector('.page.active')?.dataset.page===value,id);assert.equal(await page.locator('.page:visible').count(),1,'Exactly one page is visible');}
async function geometry(page){const g=await page.evaluate(()=>{
 const p=document.querySelector('.page.active'),s=p.querySelector('.page-scroll'),r=el=>{const b=el.getBoundingClientRect();return{x:b.x,y:b.y,width:b.width,height:b.height,right:b.right,bottom:b.bottom};};
 const rows=[...p.querySelectorAll('.stand-row,.stand-head,.leader-row')].filter(x=>x.checkVisibility()).map(x=>({...r(x),text:x.innerText}));
 const controls=[...p.querySelectorAll('button,select')].filter(x=>x.checkVisibility()).map(x=>{const b=r(x),hit=b.y>=0&&b.bottom<=innerHeight?document.elementFromPoint(b.x+b.width/2,b.y+b.height/2):null;return{tag:x.tagName,text:x.innerText||x.getAttribute('aria-label'),...b,hit:!hit?null:hit===x||x.contains(hit),disabled:x.disabled,attributes:Object.fromEntries([...x.attributes].filter(a=>a.name.startsWith('data-')||a.name.startsWith('aria-')).map(a=>[a.name,a.value]))};});
 const clipped=[...p.querySelectorAll('th,td,.stand-row>span,.stand-head>span,.leader-row>span')].filter(x=>x.checkVisibility()&&x.scrollWidth>x.clientWidth+1).map(x=>({tag:x.tagName,text:x.innerText,width:x.clientWidth,scroll:x.scrollWidth}));
 return{viewport:{width:innerWidth,height:innerHeight},page:r(p),frame:r(p.querySelector('.frame')),documentWidth:document.documentElement.scrollWidth,pageScrollWidth:p.scrollWidth,scroller:{...r(s),scrollWidth:s.scrollWidth,clientWidth:s.clientWidth,scrollHeight:s.scrollHeight,clientHeight:s.clientHeight,scrollTop:s.scrollTop},nav:r(p.querySelector('.bottom-nav')),rows,controls,clipped};
 });assert.ok(g.documentWidth<=g.viewport.width+1,'No document horizontal overflow');assert.ok(g.scroller.scrollWidth<=g.scroller.clientWidth+1,'No internal horizontal overflow');assert.ok(g.nav.x>=g.page.x-1&&g.nav.right<=g.page.right+1,'Navigation stays inside screen width');assert.ok(g.nav.y>=g.page.y-1&&g.nav.bottom<=g.page.bottom+1,'Navigation stays inside framed screen height');for(const row of g.rows)assert.ok(row.x>=g.page.x-1&&row.right<=g.page.right+1,`Table row fits frame: ${row.text}`);return g;}
async function images(page){await page.waitForFunction(()=>[...document.querySelectorAll('.page.active img')].filter(i=>i.checkVisibility()).every(i=>i.complete&&i.naturalWidth>0));const list=await page.locator('.page.active img').evaluateAll(all=>all.filter(i=>i.checkVisibility()).map(i=>{const b=i.getBoundingClientRect(),s=getComputedStyle(i),url=new URL(i.currentSrc||i.src),scale=(s.objectFit==='cover'?Math.max:Math.min)(b.width/i.naturalWidth,b.height/i.naturalHeight);return{src:url.pathname,origin:url.origin,natural:[i.naturalWidth,i.naturalHeight],rendered:[b.width,b.height],fit:s.objectFit,density:1/scale,vector:/\.svg$/.test(url.pathname),distortion:Math.abs((b.width/b.height)/(i.naturalWidth/i.naturalHeight)-1)};}));for(const i of list){assert.equal(i.origin,new URL(page.url()).origin,'All runtime images are locally bundled');assert.ok(i.vector||i.density>=1.9,`Retina source density: ${JSON.stringify(i)}`);assert.ok(['contain','cover','scale-down','none'].includes(i.fit)||i.distortion<.04,`Undistorted image ${i.src}`);}return list;}
async function capture(page,out,label){const bytes=await page.screenshot({path:path.join(out,label+'.png')});return{file:label+'.png',sha256:SHA(bytes),bytes:bytes.length,at:new Date().toISOString(),naturalAnimationPhase:true};}
async function scrollEvidence(page,out,label){const s=page.locator(NFL+' .page-scroll');const dims=await s.evaluate(x=>({height:x.scrollHeight,client:x.clientHeight}));const shots=[];const offsets=[0,Math.min(dims.height-dims.client,Math.floor(dims.client*.72)),Math.max(0,dims.height-dims.client)];for(let i=0;i<offsets.length;i++){await s.evaluate((x,y)=>x.scrollTop=y,offsets[i]);await page.waitForTimeout(100);shots.push({...await capture(page,out,`${label}-scroll-${i}`),scrollTop:await s.evaluate(x=>x.scrollTop)});}await s.evaluate(x=>x.scrollTop=0);return{...dims,shots};}
async function fullContent(page,out,label){const previous=await page.evaluate(()=>{const p=document.querySelector('.page[data-page="nfl"]'),s=p.querySelector('.page-scroll'),shell=p.closest('.app-shell'),nav=p.querySelector('.bottom-nav'),footer=p.querySelector('.nfl-source-footer'),nodes=[document.documentElement,document.body,shell,p,s,nav,footer],saved=nodes.map(e=>e.getAttribute('style'));document.documentElement.style.overflow='visible';document.body.style.overflow='visible';document.body.style.display='block';document.body.style.padding='0';document.body.style.height='auto';shell.style.margin='0 auto';shell.style.height='auto';shell.style.overflow='visible';p.style.position='relative';p.style.inset='auto';p.style.height='auto';p.style.maxHeight='none';p.style.overflow='visible';s.style.position='relative';s.style.inset='auto';s.style.height='auto';s.style.maxHeight='none';s.style.overflow='visible';s.scrollTop=0;nav.style.position='relative';nav.style.inset='auto';nav.style.width='calc(100% - 20px)';nav.style.margin='0 10px';footer.style.position='relative';footer.style.inset='auto';footer.style.margin='4px 10px 0';return saved;});try{await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const bytes=await page.screenshot({path:path.join(out,label+'-full-content.png'),fullPage:true,timeout:30000});return{file:label+'-full-content.png',sha256:SHA(bytes),bytes:bytes.length,captureOnlyUnrolledInternalScroll:true,qualification:'Entire actual rendered NFL content exposed by temporary scroller/shell height and position styles plus a stable block-flow exposure for one screenshot. Normal phone viewport captures use unmodified geometry. Source files and animation phases are unchanged.'};}finally{await page.evaluate(saved=>{const p=document.querySelector('.page[data-page="nfl"]'),nodes=[document.documentElement,document.body,p.closest('.app-shell'),p,p.querySelector('.page-scroll'),p.querySelector('.bottom-nav'),p.querySelector('.nfl-source-footer')];nodes.forEach((e,i)=>{if(saved[i]===null)e.removeAttribute('style');else e.setAttribute('style',saved[i]);});},previous);}}
async function inventory(page){return page.locator(NFL+' button,'+NFL+' select').evaluateAll(items=>items.map((e,index)=>({index,tag:e.tagName,text:e.innerText,visible:e.checkVisibility(),disabled:e.disabled,id:e.id,attrs:Object.fromEntries([...e.attributes].map(a=>[a.name,a.value])),options:e.tagName==='SELECT'?[...e.options].map(o=>({text:o.text,value:o.value})):undefined})));}
async function collect(page){const errors=[],http=[],failures=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',r=>{if(r.status()>=400)http.push({url:r.url(),status:r.status()});});page.on('requestfailed',r=>failures.push({url:r.url(),message:r.failure()?.errorText}));await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin===new URL(page.url()==='about:blank'?'http://127.0.0.1:8000':page.url()).origin||['data:','blob:','about:'].includes(u.protocol))return route.continue();external.push(u.href);return route.abort();});return{errors,http,failures,external};}
async function freePort(){const s=net.createServer();s.listen(0,'127.0.0.1');await once(s,'listening');const port=s.address().port;await new Promise(r=>s.close(r));return port;}
module.exports={ROOT,OUT,NFL,launch,runtimeManifest,SHA,WAIT,ready,active,geometry,images,capture,scrollEvidence,fullContent,inventory,freePort};
