'use strict';
const assert=require('node:assert/strict');
const {active,ready,geometry}=require('./qa.cjs');
const fieldValue=(value,isList)=>isList?(Array.isArray(value)?value.join(', '):value===null||value===undefined||value===''?'—':String(value)):(value===null||value===undefined||value===''||!Number.isFinite(Number(value))?'—':Number(value).toLocaleString('en-US',{maximumFractionDigits:2}));
async function historyValues(page,history,player,expected){
 const games=await page.locator('.player-detail:not([hidden]) [data-game-id]').evaluateAll(cards=>cards.map(c=>({id:c.dataset.gameId,fields:[...c.querySelectorAll('[data-stat-key]')].map(x=>({key:x.dataset.statKey,value:x.querySelector('b').textContent.trim()}))})));
 assert.deepEqual(games.map(g=>g.id),expected.slice(0,5),'Unpadded source-backed history order preserved');let fields=0;
 for(const g of games)for(const f of g.fields){const source=history.players[player.id].games[g.id],list=Object.hasOwn(source.rawLists||{},f.key);assert.ok(Object.hasOwn(source.stats,f.key)||Object.hasOwn(source.rawStats,f.key)||list,'Each rendered history field has an original source');const v=Object.hasOwn(source.stats,f.key)?source.stats[f.key]:list?source.rawLists[f.key]:source.rawStats[f.key];assert.equal(f.value,fieldValue(v,list),`Exact statistic ${g.id}/${f.key}`);fields++;}
 return{gameIds:games.map(g=>g.id),comparedFields:fields};
}
async function football(page){
 const target='.player-card:has(.player-detail:not([hidden]))';
 await page.waitForFunction(()=>{const c=document.querySelector('.player-card:has(.player-detail:not([hidden]))'),s=c?.querySelector('.card-perimeter-light');return c?.classList.contains('motion-track-ready')&&s&&Math.abs(s.viewBox.baseVal.height-c.getBoundingClientRect().height)<1;});
 const live=()=>page.locator(target).evaluate(c=>({ball:getComputedStyle(c.querySelector('.orbit-football')).offsetDistance,light:getComputedStyle(c.querySelector('.perimeter-light-core')).strokeDashoffset}));
 const first=await live();await page.waitForTimeout(350);const second=await live();assert.notEqual(first.ball,second.ball,'Whole-card football advances naturally');assert.notEqual(first.light,second.light,'Synchronized whole-card travelling light advances naturally');
 const footprint=await page.locator(target).evaluate(c=>{const b=c.getBoundingClientRect(),s=c.querySelector('.card-perimeter-light'),ball=c.querySelector('.orbit-football'),light=c.querySelector('.perimeter-light-core'),animations=[ball.getAnimations()[0],...[...c.querySelectorAll('.card-perimeter-light path')].map(p=>p.getAnimations()[0])];if(animations.some(a=>!a))throw Error('Whole-card animations missing');const saved=animations.map(a=>({time:a.currentTime,state:a.playState})),timing=animations[0].effect.getTiming(),edges=new Set();let distance=0,phase=0;for(const a of animations)a.pause();for(let i=0;i<32;i++){for(const a of animations)a.currentTime=timing.delay+timing.duration+i*timing.duration/32;const r=ball.getBoundingClientRect(),x=r.x+r.width/2,y=r.y+r.height/2,near=Object.entries({left:Math.abs(x-b.left),right:Math.abs(x-b.right),top:Math.abs(y-b.top),bottom:Math.abs(y-b.bottom)}).sort((a,z)=>a[1]-z[1])[0];edges.add(near[0]);distance=Math.max(distance,near[1]);phase=Math.max(phase,Math.abs(parseFloat(getComputedStyle(ball).offsetDistance)-(5-parseFloat(getComputedStyle(light).strokeDashoffset))));}animations.forEach((a,i)=>{a.currentTime=saved[i].time;if(saved[i].state==='running')a.play();});return{cardWidth:b.width,cardHeight:b.height,trackWidth:s.viewBox.baseVal.width,trackHeight:s.viewBox.baseVal.height,edges:[...edges],maximumBorderDistance:distance,maximumPhaseDifference:phase};});
 assert.ok(Math.abs(footprint.cardWidth-footprint.trackWidth)<1&&Math.abs(footprint.cardHeight-footprint.trackHeight)<1,'Track surrounds complete expanded card');assert.equal(footprint.edges.length,4,'Football visits all four complete-card edges');assert.ok(footprint.maximumBorderDistance<=12,'Football stays integrated with card perimeter');assert.ok(footprint.maximumPhaseDifference<=.1,'Football and light phase agree');return{...footprint,naturalFrames:{first,second},qualification:'Deterministic 32-phase track geometry probe restored native animation time after measuring. Evidence screenshots do not seek animation phase.'};
}
async function page3(page,base,data,history,out,label){
 await page.goto(base+'#nfl',{waitUntil:'networkidle'});await ready(page);await page.locator('#week-select').selectOption(String(data.currentWeek));await page.goto(base+'#steelers',{waitUntil:'networkidle'});await ready(page);await active(page,'steelers');assert.deepEqual(await page.locator('.page').evaluateAll(nodes=>nodes.map(node=>node.dataset.page)),['home','nfl','steelers','team-details'],'Only existing screens and the newly authorized team details route are present');await page.locator('[data-team-tab="roster"]').click();
 const player=data.roster.find(p=>p.featured&&p.position==='QB'&&history.players[p.id]?.last5?.length);assert.ok(player,'A sourced featured QB exists');
 await page.locator('[data-filter="QB"]').click();const ids=await page.locator('.player-card:visible').evaluateAll(c=>c.map(x=>x.dataset.playerId));assert.ok(ids.length&&ids.every(id=>data.roster.find(p=>p.id===id)?.filterGroup==='QB'),'QB filter keeps only verified roster quarterbacks');await page.locator('[data-filter="ALL"]').click();await page.locator(`[data-player="${player.id}"]`).click();await page.waitForFunction(()=>document.querySelector('.player-detail:not([hidden])')?.dataset.playerHistoryState==='ready');const recent=await historyValues(page,history,player,history.players[player.id].last5);
 await page.locator('.player-detail:not([hidden]) [data-history-mode="opponent"]').click();const f=data.weeks[data.currentWeek]?.fixture,o=f?(f.home_team==='PIT'?f.away_team:f.home_team):null,against=await historyValues(page,history,player,o?history.players[player.id].byOpponent[o]?.gameIds||[]:[]);await page.locator('.player-detail:not([hidden]) [data-history-mode="recent"]').click();
 await page.locator('.player-detail:not([hidden])').evaluate(e=>{const g=e.querySelector('.game-breakdown');if(g){g.open=true;const a=g.querySelector('.additional-statistics');if(a)a.open=true;}const season=e.querySelector('.season-overview');if(season)season.open=true;});await page.locator('.page.active .page-scroll').evaluate(e=>e.scrollTop=0);const perimeter=await football(page);const g=await geometry(page);await page.screenshot({path:out+'/'+label+'-steelers-regression.png'});
 await page.locator(`[data-player="${player.id}"]`).click();for(const t of ['schedule','stats','matchups','roster']){await page.locator(`[data-team-tab="${t}"]`).click();assert.equal(await page.locator('#team-panel-'+t).isVisible(),true,'All existing team panels work');}
 await page.reload({waitUntil:'networkidle'});await ready(page);await active(page,'steelers');await page.locator('.team-back').click();await active(page,'nfl');return{player:player.name,recent,against,opponent:o,football:perimeter,geometry:g,sourceDataPreserved:true,directURLAndReload:true};
}
module.exports={page3,historyValues,football};
