'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {spawn,execFileSync}=require('node:child_process');
const {once}=require('node:events');
const {ROOT,NFL,launch,runtimeManifest,SHA,WAIT,ready,active,geometry,images,capture,scrollEvidence,fullContent,inventory,freePort}=require('./qa.cjs');
const {controls}=require('./controls.cjs');
const {motion}=require('./motion.cjs');
const {page3}=require('./regression.cjs');const {paint}=require('./paint.cjs');
const args=process.argv.slice(2),arg=n=>{const i=args.indexOf(n);return i<0?null:args[i+1];};
const engine=arg('--engine')||'chromium',run=arg('--run-name'),output=arg('--output');
assert.ok(['chromium','webkit'].includes(engine),'Use --engine chromium or webkit');
assert.ok(!(args.includes('--mobile-only')&&args.includes('--desktop-only')),'Do not combine --mobile-only with --desktop-only');
assert.ok(!(args.includes('--run-name')&&args.includes('--output')),'Choose --run-name or --output');
assert.ok(args.includes('--output')?output&&!output.startsWith('--'):run&&/^[a-zA-Z0-9_-]+$/.test(run),'A unique --output path or --run-name is required to preserve previous QA');
const out=output?path.resolve(output):path.join(__dirname,run+'-'+engine);assert.ok(!fs.existsSync(out),'Never overwrite a prior QA run');fs.mkdirSync(out,{recursive:true});
const data=JSON.parse(fs.readFileSync(ROOT+'/assets/data/current.json','utf8')),history=JSON.parse(fs.readFileSync(ROOT+'/'+data.playerHistory.path,'utf8')),manifest=runtimeManifest();
const sourceHeads={gitHead:execFileSync('git',['rev-parse','HEAD'],{cwd:ROOT,encoding:'utf8'}).trim(),runtimeFiles:manifest,snapshotHash:SHA(fs.readFileSync(ROOT+'/assets/data/current.json')),historyHash:SHA(fs.readFileSync(ROOT+'/'+data.playerHistory.path))};
const report={status:'running',engine,startedAt:new Date().toISOString(),source:sourceHeads,data:{season:data.season,currentWeek:data.currentWeek,throughWeek:data.throughWeek,retrievedAt:data.retrievedAt,rosterPlayers:data.roster.length},qualification:{deviceScaleFactor:2,genuineBrowser:true,physicalIPhone:false,noSiteOrSourceDataSubstitution:true,reference:'Approved tall NFL dashboard chat attachment; original reference bytes unavailable; human comparison not registered pixel identity'},results:[]};
const hostedBase=arg('--base');let server,browser,base=hostedBase;report.hosted=!!hostedBase;report.qualification.strictTLS=!!hostedBase;report.qualification.providedCAPerRunEnvironmentOnly=!!hostedBase&&engine==='webkit';
async function testcase(viewport){
 const mobile=viewport.width<600,context=await browser.newContext({viewport,deviceScaleFactor:2,isMobile:mobile,hasTouch:mobile,timezoneId:'Australia/Sydney'}),page=await context.newPage(),result={viewport,mobile,status:'running'},errors=[],http=[],failed=[],external=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',r=>{if(r.status()>=400)http.push({url:r.url(),status:r.status()});});page.on('requestfailed',r=>failed.push({url:r.url(),message:r.failure()?.errorText}));await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin===new URL(base).origin||['data:','blob:','about:'].includes(u.protocol))return route.continue();external.push(u.href);return route.abort();});
 try{assert.equal((await page.goto(base+'#home',{waitUntil:'networkidle'})).status(),200);await ready(page);await active(page,'home');result.homeShell=await page.locator('.page.active').evaluate(e=>{const r=e.getBoundingClientRect();return{width:r.width,height:r.height,x:r.x,y:r.y};});
 await page.locator('[data-home-select="nfl"]').click();if(mobile)await page.locator('[data-home-entry]').tap();else await page.locator('[data-home-entry]').click();await active(page,'nfl');assert.equal(await page.locator('.page').count(),3,'Only original Pages 1–3 exist');assert.deepEqual(await page.evaluate(()=>window.PD_DATA),data,'UI uses exact frozen verified source data');
 result.initialGeometry=await geometry(page);assert.ok(Math.abs(result.initialGeometry.page.width-result.homeShell.width)<1,'NFL uses the same restrained width as Home');assert.ok(Math.abs(result.initialGeometry.page.height-result.homeShell.height)<1,'NFL uses the same restrained shell height as Home');if(viewport.width>=600)assert.ok(result.initialGeometry.page.width<=400.5,'Desktop/tablet NFL remains a 400px phone frame');assert.ok(result.initialGeometry.scroller.scrollHeight>result.initialGeometry.scroller.clientHeight,'Tall reference scrolls inside a framed screen');assert.ok(result.initialGeometry.nav.bottom<=viewport.height+1,'Navigation stays inside visible viewport');
 result.images=await images(page);result.buttonsBefore=await inventory(page);const label=`nfl-${viewport.width}x${viewport.height}`;
 result.initialCapture=await capture(page,out,label+'-top');await page.waitForTimeout(430);result.naturalSecondCapture=await capture(page,out,label+'-natural-second');result.scroll=await scrollEvidence(page,out,label);result.fullContent=await fullContent(page,out,label);await page.waitForTimeout(180);
 result.cornerGlyphPaint=await paint(page,out,label);console.log(`CHECK controls ${engine} ${viewport.width}`);result.controls=await controls(page,base,data,viewport.width===393);console.log(`CHECK controls passed ${engine} ${viewport.width}`);if(mobile){console.log(`CHECK motion ${engine} ${viewport.width}`);result.motion=await motion(page,base);console.log(`CHECK motion passed ${engine} ${viewport.width}`);}
 // Homeback and browser history preserve the approved shell and route boundaries.
 await page.locator(NFL+' [data-open="home"]').click();await active(page,'home');await page.goBack();await active(page,'nfl');await page.goForward();await active(page,'home');
 await page.goto(base+'#nfl',{waitUntil:'networkidle'});await ready(page);await active(page,'nfl');await page.reload({waitUntil:'networkidle'});await ready(page);await active(page,'nfl');assert.deepEqual(await page.evaluate(()=>window.PD_DATA),data,'Direct URL/reload retain verified snapshot');result.directLoadReload=true;
 if(mobile){console.log(`CHECK Page3 ${engine} ${viewport.width}`);result.page3=await page3(page,base,data,history,out,label);console.log(`CHECK Page3 passed ${engine} ${viewport.width}`);}result.finalGeometry=await geometry(page);await page.locator(NFL+' .page-scroll').evaluate(e=>e.scrollTop=0);const imageWaitAt=Date.now();result.finalVisibleImages=await images(page);await page.evaluate(async()=>{await Promise.all([...document.querySelectorAll('.page.active img')].filter(i=>i.checkVisibility()).map(i=>i.decode?.().catch(()=>{})));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});result.finalImageSettleMs=Date.now()-imageWaitAt;result.finalCapture=await capture(page,out,label+'-final');
 const genuine=failed.filter(f=>!['net::ERR_ABORTED','Load request cancelled'].includes(f.message));assert.deepEqual(errors,[],'No JavaScript or console errors');assert.deepEqual(http,[],'No failed HTTP responses');assert.deepEqual(external,[],'No external runtime dependencies');assert.deepEqual(genuine,[],'No transport failures');result.errors={javascriptAndConsole:errors,http,external,failed:genuine,cancelledNavigation:failed.filter(f=>['net::ERR_ABORTED','Load request cancelled'].includes(f.message))};result.status='passed';return result;
 }catch(e){result.status='failed';result.failure={message:e.message,stack:e.stack,errors,http,failed,external};try{await page.screenshot({path:path.join(out,`failure-${viewport.width}.png`)});result.failureDOM=await inventory(page);result.failureGeometry=await geometry(page);}catch(x){result.captureError=x.message;}return result;}finally{await context.close();}
}
(async()=>{try{if(!base){const port=await freePort();base=`http://127.0.0.1:${port}/${encodeURIComponent(path.basename(ROOT))}/`;server=spawn('python3',['-u','-m','http.server',String(port),'--bind','127.0.0.1','--directory',path.dirname(ROOT)],{stdio:'ignore'});for(let i=0;i<30;i++){try{if((await fetch(base)).status===200)break;}catch{}await WAIT(100);}}if(!base.endsWith('/'))base+='/';report.base=base;browser=await launch(engine,!!hostedBase);report.browserVersion=browser.version();const viewports=args.includes('--desktop-only')?[{width:1440,height:1000}]:args.includes('--mobile-only')?[{width:393,height:852},{width:430,height:896}]:[{width:393,height:852},{width:430,height:896},{width:320,height:700},{width:768,height:1024},{width:1440,height:1000}];for(const v of viewports){const r=await testcase(v);report.results.push(r);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));console.log(`${r.status.toUpperCase()} ${engine} ${v.width}x${v.height}${r.failure?' '+r.failure.message:''}`);}if(hostedBase){const c=await browser.newContext(),p=await c.newPage();try{await p.goto(base,{waitUntil:'networkidle'});const served=await p.evaluate(async files=>{const results=[];for(let i=0;i<files.length;i+=6)results.push(...await Promise.all(files.slice(i,i+6).map(async file=>{const r=await fetch(file,{cache:'no-store'}),b=await r.arrayBuffer();return{file,status:r.status,bytes:b.byteLength,sha256:[...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(v=>v.toString(16).padStart(2,'0')).join('')};})));return results;},Object.keys(manifest));for(const row of served){assert.equal(row.status,200,`Hosted runtime ${row.file} HTTP200`);assert.equal(row.sha256,manifest[row.file],`Hosted ${row.file} matches verified source`);}report.servedRuntime=served;}finally{await c.close();}}report.unchangedDuringQA=JSON.stringify(runtimeManifest())===JSON.stringify(manifest);assert.equal(report.unchangedDuringQA,true,'Source files are frozen during the independent QA run');report.status=report.results.every(r=>r.status==='passed')?'passed':'failed';}catch(e){report.status='failed';report.failure={message:e.message,stack:e.stack};}finally{if(browser)await browser.close();if(server){server.kill('SIGTERM');if(server.exitCode===null)await once(server,'exit');}report.completedAt=new Date().toISOString();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));console.log('Evidence '+out+'/results.json');process.exitCode=report.status==='passed'?0:1;}})();
