"use strict";
// HTML references the immutable actual PNGs; no resized/duplicate raster boards.
const fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto"),assert=require("node:assert/strict");
const sha=bytes=>crypto.createHash("sha256").update(bytes).digest("hex"),ROOT=path.resolve(__dirname,"../..");
const args=process.argv.slice(2),value=name=>{const i=args.indexOf(name);return i<0?null:args[i+1];};
const beforeDir=path.resolve(value("--before-dir")||path.join(__dirname,"baseline-local-chromium")),afterDir=path.resolve(value("--after-dir")||path.join(__dirname,"live-captures")),out=path.resolve(value("--output-dir")||path.join(__dirname,"before-after"));
const before=JSON.parse(fs.readFileSync(path.join(beforeDir,"manifest.json"))),after=JSON.parse(fs.readFileSync(path.join(afterDir,"manifest.json")));assert.equal(before.status,"complete");assert.equal(after.status,"complete");fs.mkdirSync(out,{recursive:true});
const relative=file=>path.relative(out,file).split(path.sep).join("/"),origin=report=>new URL(report.base).protocol==="https:"?"actual hosted":"actual local",escape=value=>String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll('"',"&quot;");
const rows=after.captures.filter(c=>[393,430].includes(c.viewportCssPixels.width)).map(c=>{
 const b=before.captures.find(old=>old.sport===c.sport&&old.viewportCssPixels.width===c.viewportCssPixels.width&&old.viewportCssPixels.height===c.viewportCssPixels.height);assert.ok(b,"Matching unaltered before screenshot");
 const aFile=path.join(afterDir,c.file),bFile=path.join(beforeDir,b.file);assert.equal(sha(fs.readFileSync(aFile)),c.sha256);assert.equal(sha(fs.readFileSync(bFile)),b.sha256);
 return{sport:c.sport,viewport:c.viewportCssPixels,before:{file:relative(bFile),sha256:b.sha256,engine:before.engine,location:origin(before)},after:{file:relative(aFile),sha256:c.sha256,engine:after.engine,location:origin(after)}};
});assert.equal(rows.length,8,"Exactly eight primary sport/phone comparisons");
const report={status:"complete",createdAt:new Date().toISOString(),comparison:"Previous actual mobile composition versus refined actual mobile output; original PNGs referenced without duplication",approvedSource:"User-attached final four-sport Home gate concept in chat; original source bytes unavailable",pixelRegisteredConceptComparison:false,sourcePixelsAltered:false,duplicatePngBytesCreated:0,beforeManifest:{file:relative(path.join(beforeDir,"manifest.json")),sha256:sha(fs.readFileSync(path.join(beforeDir,"manifest.json")))},afterManifest:{file:relative(path.join(afterDir,"manifest.json")),sha256:sha(fs.readFileSync(path.join(afterDir,"manifest.json")))},rows};fs.writeFileSync(path.join(out,"manifest.json"),JSON.stringify(report,null,2)+"\n");
const blocks=rows.map(row=>`<section><h2>${row.sport.toUpperCase()} · ${row.viewport.width}×${row.viewport.height}</h2><div class="pair">${["before","after"].map(side=>`<figure><figcaption>${side==="before"?"Previous composition":"Refined composition"}<small>${escape(row[side].engine)} · ${escape(row[side].location)} · DPR2 · motion running</small></figcaption><a href="${escape(row[side].file)}"><img src="${escape(row[side].file)}" width="${row.viewport.width}" height="${row.viewport.height}" alt="${side} actual ${row.sport} screenshot"></a></figure>`).join("")}</div></section>`).join("\n");
fs.writeFileSync(path.join(out,"index.html"),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Project Dollar — actual before/after</title><style>body{margin:0;padding:24px;background:#03080e;color:#edf5ff;font:15px system-ui;line-height:1.5}h1{font-size:25px}h2{font-size:18px;margin-top:32px}p{max-width:1050px}a{color:#62d9ff}.pair{display:flex;gap:24px;overflow-x:auto;align-items:flex-start}figure{margin:0;flex:none}figcaption{font-weight:600;margin-bottom:10px}small{display:block;color:#abb8cb;font-weight:400}img{display:block;max-width:430px;height:auto;border:1px solid #314c61}</style><h1>Project Dollar — actual before/after</h1><p>Eight pairs reference the original, unmodified browser PNGs. Engine and local/hosted location are labelled explicitly; continuous motion naturally differs in phase. No duplicate raster boards or generated screenshots are used.</p><p>The approved source was the user’s chat attachment. Its original bytes are unavailable, so this gallery is actual-before/actual-after evidence, not a registered concept composite. Independent visual comparison against the approved attached render remains required.</p><a href="manifest.json">Original image and manifest hashes</a>${blocks}</html>`);
console.log(`Saved 8 HTML comparisons with 0 duplicate PNG bytes: ${path.relative(ROOT,out)}/index.html`);
