'use strict';
const fs=require('node:fs'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const ROOT='/workspace/project-dollers',q=require(ROOT+'/qa/matchup-breakdown/qa.cjs'),BASE='http://127.0.0.1:8886/project-dollers/',APP='/workspace/recovery-qa/home-synchronized-entrance/baseline-server/project-dollers',OUT=ROOT+'/qa/home-synchronized-entrance/baseline-webkit',HOME='[data-page="home"]',sha=b=>crypto.createHash('sha256').update(b).digest('hex');
assert.ok(!fs.existsSync(OUT));fs.mkdirSync(OUT,{recursive:true});fs.copyFileSync(__filename,OUT+'/executed-helper.cjs');
const exported=JSON.parse(fs.readFileSync('/workspace/recovery-qa/home-synchronized-entrance/baseline-source.json'));
const names=['index.html',...Object.keys(exported.sourceFiles).filter(p=>/^assets\/home[^/]*\.(css|js)$/.test(p)||/^assets\/home\/(aperture-refined|gem-atlas|gate-brand|gate-scenes-(nfl|nba|nrl|ufc))\.webp$/.test(p))];
const source=Object.fromEntries(names.map(p=>[p,exported.sourceFiles[p]]));
const r={status:'running',startedAt:new Date().toISOString(),engine:'webkit',base:BASE,baselineCommit:exported.commit,source,nativeInput:true,DOMStyleClockResponseSubstitution:false,physicalIPhone:false,registeredReferenceComparison:false,helperSha256:sha(fs.readFileSync(__filename)),results:[]};
let browser;const save=()=>fs.writeFileSync(OUT+'/results.json',JSON.stringify(r,null,2)+'\n');save();
async function ready(page){await page.waitForFunction(()=>document.querySelector('.page.active')?.dataset.page==='home');await page.evaluate(async()=>document.fonts.ready);await page.waitForFunction(()=>[...document.querySelectorAll('.page.active img')].filter(i=>i.checkVisibility()).every(i=>i.complete&&i.naturalWidth>0));await page.bringToFront();}
async function state(page){return page.locator(HOME).evaluate(h=>{const rect=e=>{if(!e)return null;const b=e.getBoundingClientRect();return{x:b.x,y:b.y,width:b.width,height:b.height,right:b.right,bottom:b.bottom};};const motion=e=>{const c=getComputedStyle(e),a=e.getAnimations().filter(a=>a.effect?.target===e).map(a=>({name:a.animationName,startTime:a.startTime,currentTime:a.currentTime,playState:a.playState,pending:a.pending,progress:a.effect.getComputedTiming().progress,duration:a.effect.getTiming().duration,delay:a.effect.getTiming().delay,iterations:a.effect.getTiming().iterations}));return{class:e.getAttribute('class'),pathLength:e.getAttribute('pathLength'),totalLength:e.tagName.toLowerCase()==='path'?e.getTotalLength():null,dash:c.strokeDashoffset,dasharray:c.strokeDasharray,duration:c.animationDuration,delay:c.animationDelay,play:c.animationPlayState,clocks:a};};return{at:performance.now(),sport:h.dataset.homeSport,homeState:h.dataset.homeMotionState,opacity:getComputedStyle(h).opacity,viewport:{width:innerWidth,height:innerHeight},docWidth:document.documentElement.scrollWidth,brand:rect(h.querySelector('.brand')),gate:rect(h.querySelector('.aperture-gate')),entry:rect(h.querySelector('[data-home-entry]')),dock:rect(h.querySelector('.home-sport-dock')),ring:[...h.querySelectorAll('.aperture-neon-runner,.aperture-metal-runner')].map(motion),selectorHot:[...h.querySelectorAll('.home-gem-selector-hot')].map(motion),entryClocks:h.getAnimations({subtree:true}).filter(a=>a.effect?.target?.closest('[data-home-entry]')).map(a=>({name:a.animationName,target:a.effect.target.className,pseudo:a.effect.pseudoElement||null,startTime:a.startTime,time:a.currentTime,state:a.playState,progress:a.effect.getComputedTiming().progress,duration:a.effect.getTiming().duration,delay:a.effect.getTiming().delay,iterations:a.effect.getTiming().iterations})),images:[...h.querySelectorAll('img')].filter(i=>i.checkVisibility()).map(i=>({src:i.currentSrc,naturalWidth:i.naturalWidth,naturalHeight:i.naturalHeight,fit:getComputedStyle(i).objectFit,rect:rect(i)}))};});}
async function capture(page,file){await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const bytes=await page.screenshot({path:OUT+'/'+file,animations:'allow'});return{file,sha256:sha(bytes),bytes:bytes.length,naturalAnimationPhase:true};}
(async()=>{try{browser=await q.launch('webkit',false);r.browser=browser.version();for(const config of[{viewport:{width:393,height:852},sports:['nfl','ufc']},{viewport:{width:430,height:896},sports:['nba','nrl']}]){const ctx=await browser.newContext({viewport:config.viewport,deviceScaleFactor:2,isMobile:true,hasTouch:true}),page=await ctx.newPage(),row={viewport:config.viewport,originals:[],samples:[],errors:[],http:[],failures:[]};r.results.push(row);page.on('pageerror',e=>row.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')row.errors.push(m.text());});page.on('response',v=>{if(v.status()>=400)row.http.push({url:v.url(),status:v.status()});});page.on('requestfailed',v=>row.failures.push({url:v.url(),error:v.failure()?.errorText}));try{const res=await page.goto(BASE+'#home',{waitUntil:'networkidle'});assert.equal(res.status(),200);row.actualRootSha256=sha(await res.body());assert.equal(row.actualRootSha256,source['index.html']);await ready(page);for(const sport of config.sports){if(sport!=='nfl')await page.locator(HOME+' [data-home-select="'+sport+'"]').tap();await ready(page);const before=await state(page),original=await capture(page,`home-${sport}-${config.viewport.width}x${config.viewport.height}.png`),after=await state(page);row.originals.push({sport,...original,before,after});for(const pause of[0,400,700]){if(pause)await page.waitForTimeout(pause);row.samples.push({sport,requestedWait:pause,state:await state(page)});}save();console.log(JSON.stringify({capture:original.file,baselineCommit:r.baselineCommit}));}assert.deepEqual(row.errors,[]);assert.deepEqual(row.http,[]);assert.deepEqual(row.failures,[]);row.status='passed';}finally{await ctx.close();save();}}r.sourceStable=Object.entries(source).every(([p,h])=>sha(fs.readFileSync(APP+'/'+p))===h);assert.ok(r.sourceStable);r.status='passed';}catch(e){r.status='failed';r.failure={message:e.message,stack:e.stack};process.exitCode=1;}finally{if(browser)await browser.close();r.browserClosed=true;r.completedAt=new Date().toISOString();save();console.log(JSON.stringify({status:r.status,report:OUT+'/results.json',sha256:sha(fs.readFileSync(OUT+'/results.json')),failure:r.failure}));}})();
