'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const ROOT='/workspace/project-dollers',q=require(ROOT+'/qa/matchup-breakdown/qa.cjs'),OUT='/workspace/recovery-qa/home-reference-correction/webkit-return-repro',BASE='http://127.0.0.1:8876/project-dollers/',HOME='[data-page="home"]',SHA=b=>crypto.createHash('sha256').update(b).digest('hex');
assert.ok(!fs.existsSync(OUT));fs.mkdirSync(OUT,{recursive:true});fs.copyFileSync(__filename,OUT+'/executed-helper.cjs');
const sources=JSON.parse(fs.readFileSync(ROOT+'/qa/home-reference-correction/final-webkit/results.json')).source,report={status:'running',startedAt:new Date().toISOString(),source:sources,engine:'webkit',base:BASE,nativeInputs:true,DOMCSSClockResponseSubstitution:false,results:[]};
let browser;const save=()=>fs.writeFileSync(OUT+'/results.json',JSON.stringify(report,null,2)+'\n');
async function ready(page,id){await page.waitForFunction(v=>document.querySelector('.page.active')?.dataset.page===v,id);await page.evaluate(async()=>document.fonts.ready);await page.bringToFront();}
async function sample(page){return page.locator(HOME).evaluate(h=>({at:performance.now(),state:h.dataset.homeMotionState,reason:h.dataset.homeMotionReason,active:h.classList.contains('active'),hidden:h.hidden,visibility:document.visibilityState,clocks:h.getAnimations({subtree:true}).filter(a=>a.effect?.getComputedTiming().iterations===Infinity).map(a=>({name:a.animationName,time:a.currentTime,state:a.playState,pending:a.pending,targetClass:a.effect.target.getAttribute('class'),pseudo:a.effect.pseudoElement||null,cssPlay:getComputedStyle(a.effect.target,a.effect.pseudoElement).animationPlayState}))}));}
async function capture(page,file){const bytes=await page.screenshot({path:OUT+'/'+file,animations:'allow'});return{file,sha256:SHA(bytes),bytes:bytes.length};}
(async()=>{try{browser=await q.launch('webkit',false);for(const viewport of[{width:393,height:852},{width:430,height:896}]){const context=await browser.newContext({viewport,deviceScaleFactor:2,isMobile:true,hasTouch:true}),page=await context.newPage(),r={viewport,errors:[],http:[],samples:[]};report.results.push(r);page.on('pageerror',e=>r.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')r.errors.push(m.text());});page.on('response',v=>{if(v.status()>=400)r.http.push({url:v.url(),status:v.status()});});try{await page.goto(BASE+'#home',{waitUntil:'networkidle'});await ready(page,'home');await page.waitForFunction(()=>[...document.querySelectorAll('.page.active img')].filter(i=>i.checkVisibility()).every(i=>i.complete&&i.naturalWidth>0));r.initialPaint=await capture(page,`home-${viewport.width}-initial.png`);r.initial=await sample(page);await page.locator(HOME+' [data-home-entry]').tap();await ready(page,'nfl');await page.waitForFunction(()=>document.documentElement.dataset.dataReady==='true'&&window.PD_DATA?.roster?.length);r.inactive=await sample(page);await page.locator('[data-page="nfl"] [data-open="home"]').first().tap();await ready(page,'home');r.immediateBeforePaint=await sample(page);for(const [label,delay] of[['paint-0',0],['paint-100',100],['paint-400',300],['paint-1000',600]]){if(delay)await page.waitForTimeout(delay);const before=await sample(page),paint=await capture(page,`home-${viewport.width}-${label}.png`),after=await sample(page);r.samples.push({label,before,paint,after});save();console.log(JSON.stringify({viewport:viewport.width,label,beforeCounts:before.clocks.reduce((o,c)=>(o[c.state]=(o[c.state]||0)+1,o),{}),afterCounts:after.clocks.reduce((o,c)=>(o[c.state]=(o[c.state]||0)+1,o),{}),minTime:Math.min(...after.clocks.map(c=>c.time))}));}r.status='captured';}finally{await context.close();save();}}report.sourceStable=Object.entries(sources).every(([p,sha])=>SHA(fs.readFileSync(ROOT+'/'+p))===sha);report.status='captured';}catch(e){report.status='failed';report.failure={message:e.message,stack:e.stack};process.exitCode=1;}finally{if(browser)await browser.close();report.browserClosed=true;report.completedAt=new Date().toISOString();save();console.log(JSON.stringify({status:report.status,report:OUT+'/results.json',sha256:SHA(fs.readFileSync(OUT+'/results.json')),sourceStable:report.sourceStable}));}})();
